//! Error types specific to the high-level API.

use std::fmt;
use thiserror::Error;

/// Errors that can occur during AI operations.
#[derive(Debug, Error)]
pub enum AIError {
    /// No output was generated by the model.
    #[error("No output was generated by the model")]
    NoOutputGenerated,

    /// No speech was generated.
    #[error("No speech was generated")]
    NoSpeechGenerated,

    /// No image was generated.
    #[error("No image was generated")]
    NoImageGenerated,

    /// No video was generated.
    #[error("No video was generated")]
    NoVideoGenerated,

    /// No video was generated (with response metadata).
    #[error("{0}")]
    NoVideoGeneratedWithResponse(#[from] NoVideoGeneratedError),

    /// No transcript was generated.
    #[error("No transcript was generated")]
    NoTranscriptGenerated,

    /// No object was generated.
    #[error("No object was generated")]
    NoObjectGenerated,

    /// Invalid argument provided.
    #[error("Invalid argument: {0}")]
    InvalidArgument(String),

    /// Maximum steps exceeded.
    #[error("Maximum steps exceeded: {0} steps")]
    MaxStepsExceeded(u32),

    /// Tool execution failed.
    #[error("Tool execution failed: {0}")]
    ToolExecutionFailed(String),

    /// Schema validation failed.
    #[error("Schema validation failed: {0}")]
    SchemaValidation(String),

    /// Invalid stream part encountered.
    #[error("{0}")]
    InvalidStreamPart(#[from] InvalidStreamPartError),

    /// Invalid tool approval.
    #[error("{0}")]
    InvalidToolApproval(#[from] InvalidToolApprovalError),

    /// Invalid tool input.
    #[error("{0}")]
    InvalidToolInput(#[from] InvalidToolInputError),

    /// Missing tool results.
    #[error("{0}")]
    MissingToolResults(#[from] MissingToolResultsError),

    /// No such tool.
    #[error("{0}")]
    NoSuchTool(#[from] NoSuchToolError),

    /// Tool call not found for approval.
    #[error("{0}")]
    ToolCallNotFoundForApproval(#[from] ToolCallNotFoundForApprovalError),

    /// Tool call repair failed.
    #[error("{0}")]
    ToolCallRepair(#[from] ToolCallRepairError),

    /// Unsupported model version.
    #[error("{0}")]
    UnsupportedModelVersion(#[from] UnsupportedModelVersionError),

    /// Provider error.
    #[error("Provider error: {0}")]
    ProviderError(#[from] vercel_ai_provider::AISdkError),

    /// Operation timed out.
    #[error("Timeout: {0}")]
    Timeout(String),

    /// Invalid configuration.
    #[error("Invalid configuration: {0}")]
    InvalidConfig(String),

    /// JSON error.
    #[error("JSON error: {0}")]
    JsonError(#[from] serde_json::Error),
}

impl AIError {
    /// Create a new error with a type and message.
    pub fn new(kind: &str, message: impl Into<String>) -> Self {
        match kind {
            "NoOutputGenerated" => Self::NoOutputGenerated,
            "NoSpeechGenerated" => Self::NoSpeechGenerated,
            "NoImageGenerated" => Self::NoImageGenerated,
            "NoVideoGenerated" => Self::NoVideoGenerated,
            "NoTranscriptGenerated" => Self::NoTranscriptGenerated,
            "NoObjectGenerated" => Self::NoObjectGenerated,
            "InvalidArgument" => Self::InvalidArgument(message.into()),
            "MaxStepsExceeded" => Self::MaxStepsExceeded(message.into().parse().unwrap_or(0)),
            "ToolExecutionFailed" => Self::ToolExecutionFailed(message.into()),
            "SchemaValidation" => Self::SchemaValidation(message.into()),
            _ => Self::InvalidArgument(format!("{}: {}", kind, message.into())),
        }
    }

    /// Check if this is a no output generated error.
    pub fn is_no_output(&self) -> bool {
        matches!(self, Self::NoOutputGenerated)
    }

    /// Check if this is a no speech generated error.
    pub fn is_no_speech(&self) -> bool {
        matches!(self, Self::NoSpeechGenerated)
    }

    /// Check if this is a no image generated error.
    pub fn is_no_image(&self) -> bool {
        matches!(self, Self::NoImageGenerated)
    }

    /// Check if this is a no video generated error.
    pub fn is_no_video(&self) -> bool {
        matches!(self, Self::NoVideoGenerated)
    }

    /// Check if this is a no transcript generated error.
    pub fn is_no_transcript(&self) -> bool {
        matches!(self, Self::NoTranscriptGenerated)
    }

    /// Check if this is a no object generated error.
    pub fn is_no_object(&self) -> bool {
        matches!(self, Self::NoObjectGenerated)
    }
}

/// Error thrown when no output is generated.
#[derive(Debug, Error)]
#[error("No output generated")]
pub struct NoOutputGeneratedError {
    /// The prompt that was sent to the model.
    pub prompt: Option<String>,
    /// The model that was used.
    pub model_id: Option<String>,
}

impl NoOutputGeneratedError {
    /// Create a new no output generated error.
    pub fn new() -> Self {
        Self {
            prompt: None,
            model_id: None,
        }
    }

    /// Add the prompt that was sent to the model.
    pub fn with_prompt(mut self, prompt: impl Into<String>) -> Self {
        self.prompt = Some(prompt.into());
        self
    }

    /// Add the model ID that was used.
    pub fn with_model_id(mut self, model_id: impl Into<String>) -> Self {
        self.model_id = Some(model_id.into());
        self
    }
}

impl Default for NoOutputGeneratedError {
    fn default() -> Self {
        Self::new()
    }
}

/// Error thrown when an invalid argument is provided.
#[derive(Debug, Error)]
#[error("Invalid argument: {message}")]
pub struct InvalidArgumentError {
    /// The error message.
    pub message: String,
    /// The argument name.
    pub argument: Option<String>,
}

impl InvalidArgumentError {
    /// Create a new invalid argument error.
    pub fn new(message: impl Into<String>) -> Self {
        Self {
            message: message.into(),
            argument: None,
        }
    }

    /// Add the argument name.
    pub fn with_argument(mut self, argument: impl Into<String>) -> Self {
        self.argument = Some(argument.into());
        self
    }
}

/// Error thrown when schema validation fails.
#[derive(Debug, Error)]
#[error("Schema validation failed: {message}")]
pub struct SchemaValidationError {
    /// The error message.
    pub message: String,
    /// The value that failed validation.
    pub value: Option<serde_json::Value>,
    /// The schema that was used.
    pub schema: Option<serde_json::Value>,
}

impl SchemaValidationError {
    /// Create a new schema validation error.
    pub fn new(message: impl Into<String>) -> Self {
        Self {
            message: message.into(),
            value: None,
            schema: None,
        }
    }

    /// Add the value that failed validation.
    pub fn with_value(mut self, value: serde_json::Value) -> Self {
        self.value = Some(value);
        self
    }

    /// Add the schema that was used.
    pub fn with_schema(mut self, schema: serde_json::Value) -> Self {
        self.schema = Some(schema);
        self
    }
}

/// Response metadata for video generation.
#[derive(Debug, Clone)]
pub struct VideoModelResponseMetadata {
    /// The timestamp of the response.
    pub timestamp: Option<chrono::DateTime<chrono::Utc>>,
    /// The model ID used.
    pub model_id: Option<String>,
    /// Response headers.
    pub headers: std::collections::HashMap<String, String>,
}

impl VideoModelResponseMetadata {
    /// Create new response metadata.
    pub fn new() -> Self {
        Self {
            timestamp: None,
            model_id: None,
            headers: std::collections::HashMap::new(),
        }
    }

    /// Set the timestamp.
    pub fn with_timestamp(mut self, timestamp: chrono::DateTime<chrono::Utc>) -> Self {
        self.timestamp = Some(timestamp);
        self
    }

    /// Set the model ID.
    pub fn with_model_id(mut self, model_id: impl Into<String>) -> Self {
        self.model_id = Some(model_id.into());
        self
    }
}

impl Default for VideoModelResponseMetadata {
    fn default() -> Self {
        Self::new()
    }
}

/// Error thrown when no video is generated.
#[derive(Debug, Error)]
#[error("No video generated")]
pub struct NoVideoGeneratedError {
    /// Response metadata from the provider.
    pub responses: Vec<VideoModelResponseMetadata>,
}

impl NoVideoGeneratedError {
    /// Create a new no video generated error.
    pub fn new() -> Self {
        Self {
            responses: Vec::new(),
        }
    }

    /// Create with responses.
    pub fn with_responses(responses: Vec<VideoModelResponseMetadata>) -> Self {
        Self { responses }
    }

    /// Add a response.
    pub fn with_response(mut self, response: VideoModelResponseMetadata) -> Self {
        self.responses.push(response);
        self
    }
}

impl Default for NoVideoGeneratedError {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// Tool-related errors
// ============================================================================

/// Error thrown when an invalid stream part is encountered.
#[derive(Debug, Error)]
#[error("Invalid stream part: {message}")]
pub struct InvalidStreamPartError {
    /// The error message.
    pub message: String,
}

impl InvalidStreamPartError {
    /// Create a new invalid stream part error.
    pub fn new(message: impl Into<String>) -> Self {
        Self {
            message: message.into(),
        }
    }
}

/// Error thrown when a tool approval response references an unknown approval ID.
#[derive(Debug, Error)]
#[error(
    "Tool approval response references unknown approvalId: \"{approval_id}\". No matching tool-approval-request found in message history."
)]
pub struct InvalidToolApprovalError {
    /// The approval ID that was not found.
    pub approval_id: String,
}

impl InvalidToolApprovalError {
    /// Create a new invalid tool approval error.
    pub fn new(approval_id: impl Into<String>) -> Self {
        Self {
            approval_id: approval_id.into(),
        }
    }
}

/// Error thrown when tool input validation fails.
#[derive(Debug, Clone, Error)]
#[error("Invalid input for tool {tool_name}: {message}")]
pub struct InvalidToolInputError {
    /// The tool name.
    pub tool_name: String,
    /// The tool input that was invalid.
    pub tool_input: String,
    /// The error message.
    pub message: String,
    /// The underlying cause.
    pub cause: Option<String>,
}

impl InvalidToolInputError {
    /// Create a new invalid tool input error.
    pub fn new(tool_name: impl Into<String>, tool_input: impl Into<String>) -> Self {
        Self {
            tool_name: tool_name.into(),
            tool_input: tool_input.into(),
            message: String::new(),
            cause: None,
        }
    }

    /// Set the error message.
    pub fn with_message(mut self, message: impl Into<String>) -> Self {
        self.message = message.into();
        self
    }

    /// Set the underlying cause.
    pub fn with_cause(mut self, cause: impl Into<String>) -> Self {
        self.cause = Some(cause.into());
        self
    }
}

/// Error thrown when tool results are missing for tool calls.
#[derive(Debug, Error)]
pub struct MissingToolResultsError {
    /// The tool call IDs that are missing results.
    pub tool_call_ids: Vec<String>,
}

impl fmt::Display for MissingToolResultsError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let plural = if self.tool_call_ids.len() > 1 {
            "s"
        } else {
            ""
        };
        let verb = if self.tool_call_ids.len() > 1 {
            "are"
        } else {
            "is"
        };
        write!(
            f,
            "Tool result{} {} missing for tool call{} {}",
            plural,
            verb,
            plural,
            self.tool_call_ids.join(", ")
        )
    }
}

impl MissingToolResultsError {
    /// Create a new missing tool results error.
    pub fn new(tool_call_ids: Vec<String>) -> Self {
        Self { tool_call_ids }
    }
}

/// Error thrown when a model tries to call an unavailable tool.
#[derive(Debug, Clone, Error)]
pub struct NoSuchToolError {
    /// The tool name that was requested.
    pub tool_name: String,
    /// The available tools.
    pub available_tools: Option<Vec<String>>,
}

impl fmt::Display for NoSuchToolError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match &self.available_tools {
            Some(tools) => write!(
                f,
                "Model tried to call unavailable tool '{}'. Available tools: {}.",
                self.tool_name,
                tools.join(", ")
            ),
            None => write!(
                f,
                "Model tried to call unavailable tool '{}'. No tools are available.",
                self.tool_name
            ),
        }
    }
}

impl NoSuchToolError {
    /// Create a new no such tool error.
    pub fn new(tool_name: impl Into<String>) -> Self {
        Self {
            tool_name: tool_name.into(),
            available_tools: None,
        }
    }

    /// Set the available tools.
    pub fn with_available_tools(mut self, tools: Vec<String>) -> Self {
        self.available_tools = Some(tools);
        self
    }
}

/// Error thrown when a tool call is not found for an approval request.
#[derive(Debug, Error)]
#[error("Tool call \"{tool_call_id}\" not found for approval request \"{approval_id}\".")]
pub struct ToolCallNotFoundForApprovalError {
    /// The tool call ID.
    pub tool_call_id: String,
    /// The approval ID.
    pub approval_id: String,
}

impl ToolCallNotFoundForApprovalError {
    /// Create a new tool call not found for approval error.
    pub fn new(tool_call_id: impl Into<String>, approval_id: impl Into<String>) -> Self {
        Self {
            tool_call_id: tool_call_id.into(),
            approval_id: approval_id.into(),
        }
    }
}

/// Error thrown when tool call repair fails.
#[derive(Debug, Clone, Error)]
#[error("Error repairing tool call: {message}")]
pub struct ToolCallRepairError {
    /// The error message.
    pub message: String,
    /// The original error that triggered the repair.
    pub original_error: ToolCallRepairOriginalError,
}

/// The original error that triggered a tool call repair.
#[derive(Debug, Clone)]
pub enum ToolCallRepairOriginalError {
    /// The tool was not found.
    NoSuchTool(NoSuchToolError),
    /// The tool input was invalid.
    InvalidToolInput(InvalidToolInputError),
}

impl ToolCallRepairError {
    /// Create a new tool call repair error.
    pub fn new(message: impl Into<String>, original_error: ToolCallRepairOriginalError) -> Self {
        Self {
            message: message.into(),
            original_error,
        }
    }
}

/// Error thrown when a model with an unsupported version is used.
#[derive(Debug, Error)]
#[error(
    "Unsupported model version {version} for provider \"{provider}\" and model \"{model_id}\". AI SDK 5 only supports models that implement specification version \"v2\"."
)]
pub struct UnsupportedModelVersionError {
    /// The unsupported version.
    pub version: String,
    /// The provider name.
    pub provider: String,
    /// The model ID.
    pub model_id: String,
}

impl UnsupportedModelVersionError {
    /// Create a new unsupported model version error.
    pub fn new(
        version: impl Into<String>,
        provider: impl Into<String>,
        model_id: impl Into<String>,
    ) -> Self {
        Self {
            version: version.into(),
            provider: provider.into(),
            model_id: model_id.into(),
        }
    }
}
