//! Tool orchestration — batch execution with hook integration.
//!
//! TS: services/tools/toolOrchestration.ts (900 LOC) + toolExecution.ts (1.7K)
//! Runs tools through the permission → execute → hook pipeline.

use coco_types::Message;
use coco_types::ToolId;
use serde_json::Value;
use std::sync::Arc;

use crate::context::ToolUseContext;
use crate::executor::PendingToolCall;
use crate::executor::StreamingToolExecutor;
use crate::executor::ToolCallResult;
use crate::registry::ToolRegistry;

/// Result of orchestrated tool execution with metadata.
#[derive(Debug)]
pub struct OrchestratedResult {
    pub tool_results: Vec<ToolCallResult>,
    /// New messages generated by tools (e.g., file change notifications).
    pub new_messages: Vec<Message>,
    /// Tools that were denied by permissions.
    pub denied_tools: Vec<String>,
    /// Total execution time in milliseconds.
    pub total_duration_ms: i64,
}

/// Run a batch of tool calls through the full orchestration pipeline.
///
/// Steps:
/// 1. Permission check each tool
/// 2. Partition into safe/unsafe batches  
/// 3. Execute via StreamingToolExecutor
/// 4. Collect results + new messages
/// 5. Track denied tools for telemetry
pub async fn run_tools(
    tool_calls: Vec<(String, String, Value)>, // (tool_use_id, tool_name, input)
    tools: &Arc<ToolRegistry>,
    ctx: &ToolUseContext,
) -> OrchestratedResult {
    let start = std::time::Instant::now();
    let mut denied_tools = Vec::new();
    let mut pending = Vec::new();

    // Phase 1: Permission checks
    for (tool_use_id, tool_name, input) in &tool_calls {
        let tool_id: ToolId = tool_name
            .parse()
            .unwrap_or_else(|_| ToolId::Custom(tool_name.clone()));

        if let Some(tool) = tools.get(&tool_id) {
            let decision = tool.check_permissions(input, ctx).await;
            match decision {
                coco_types::PermissionDecision::Deny { .. } => {
                    denied_tools.push(tool_name.clone());
                    continue;
                }
                coco_types::PermissionDecision::Ask { .. }
                | coco_types::PermissionDecision::Allow { .. } => {}
            }

            pending.push(PendingToolCall {
                tool_use_id: tool_use_id.clone(),
                tool: tool.clone(),
                input: input.clone(),
            });
        }
    }

    // Phase 2: Execute via batch executor
    let executor = StreamingToolExecutor::new();
    let tool_results = executor.execute_all(pending, ctx).await;

    // Phase 3: Collect new messages from tool results
    let mut new_messages = Vec::new();
    for result in &tool_results {
        if let Ok(ref tr) = result.result {
            new_messages.extend(tr.new_messages.iter().cloned());
        }
    }

    let total_duration_ms = start.elapsed().as_millis() as i64;

    OrchestratedResult {
        tool_results,
        new_messages,
        denied_tools,
        total_duration_ms,
    }
}

/// Check if any tool in a batch is destructive.
pub fn has_destructive_tool(tool_calls: &[(String, String, Value)], tools: &ToolRegistry) -> bool {
    tool_calls.iter().any(|(_, name, input)| {
        let tool_id: ToolId = name
            .parse()
            .unwrap_or_else(|_| ToolId::Custom(name.clone()));
        tools.get(&tool_id).is_some_and(|t| t.is_destructive(input))
    })
}

/// Get the tool result budget — maximum characters per tool result.
///
/// TS: TOOL_RESULT_BUDGET from constants
pub const TOOL_RESULT_BUDGET_CHARS: usize = 100_000;

/// Truncate a tool result to the budget.
pub fn truncate_tool_result(result: &str) -> String {
    if result.len() <= TOOL_RESULT_BUDGET_CHARS {
        result.to_string()
    } else {
        format!(
            "{}...\n[output truncated: {} chars total, showing first {}]",
            &result[..TOOL_RESULT_BUDGET_CHARS],
            result.len(),
            TOOL_RESULT_BUDGET_CHARS,
        )
    }
}

#[cfg(test)]
#[path = "orchestration.test.rs"]
mod tests;
