use serde::Deserialize;
use serde::Serialize;
use uuid::Uuid;

use crate::AttachmentKind;
use crate::CompactTrigger;
use crate::PermissionMode;
use crate::TokenUsage;
use crate::ToolId;

use super::AttachmentBody;
use super::SilentPayload;
use super::aliases::LlmMessage;
use super::attachment_body::AlreadyReadFilePayload;
use super::attachment_body::AttachmentExtras;
use super::attachment_body::CommandPermissionsPayload;
use super::attachment_body::DynamicSkillPayload;
use super::attachment_body::EditedImageFilePayload;
use super::attachment_body::HookCancelledPayload;
use super::attachment_body::HookErrorDuringExecutionPayload;
use super::attachment_body::HookNonBlockingErrorPayload;
use super::attachment_body::HookPermissionDecisionPayload;
use super::attachment_body::HookSystemMessagePayload;
use super::attachment_body::MaxTurnsReachedPayload;
use super::attachment_body::SkillDiscoveryPayload;
use super::attachment_body::StructuredOutputPayload;

/// Top-level message enum.
///
/// Tool-use summaries are intentionally **not** a `Message` variant —
/// they're UI-only polish (mobile-row label generated by the Fast
/// model post-turn). The engine emits
/// [`crate::ServerNotification::ToolUseSummary`] for SDK consumers
/// and the TUI side-caches the text without writing it to
/// `MessageHistory`. Keeping UI-only data out of the authoritative
/// transcript upholds I-3 from
/// `docs/coco-rs/engine-tui-unified-transcript-plan.md`.
#[cfg_attr(feature = "schema", derive(schemars::JsonSchema))]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum Message {
    User(UserMessage),
    Assistant(AssistantMessage),
    System(SystemMessage),
    Attachment(AttachmentMessage),
    ToolResult(ToolResultMessage),
    Progress(ProgressMessage),
    Tombstone(TombstoneMessage),
}

/// Visibility axes for a [`Message`] — orthogonal API × UI flags.
///
/// Mirrors the two-axis filter pattern: `normalizeAttachmentForAPI`
/// controls `api`, `nullRenderingAttachments.ts` controls `ui`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Visibility {
    /// Does this message's content reach the LLM API?
    pub api: bool,
    /// Does this message render in the user-visible UI transcript?
    pub ui: bool,
}

impl Visibility {
    pub const BOTH: Self = Self {
        api: true,
        ui: true,
    };
    pub const API_ONLY: Self = Self {
        api: true,
        ui: false,
    };
    pub const UI_ONLY: Self = Self {
        api: false,
        ui: true,
    };
    pub const NEITHER: Self = Self {
        api: false,
        ui: false,
    };
}

impl Message {
    pub fn uuid(&self) -> Option<&Uuid> {
        match self {
            Self::User(m) => Some(&m.uuid),
            Self::Assistant(m) => Some(&m.uuid),
            Self::System(m) => Some(m.uuid()),
            Self::Attachment(m) => Some(&m.uuid),
            Self::ToolResult(m) => Some(&m.uuid),
            Self::Progress(_) => None,
            Self::Tombstone(m) => Some(&m.uuid),
        }
    }

    /// Single source of truth for API × UI filtering.
    ///
    /// - `User`/`Assistant`/`ToolResult` — both axes true unless the user
    ///   message is meta (hidden from UI only).
    /// - `System` — API-only (rendered as meta user on API, hidden from UI).
    /// - `Attachment` — derived from [`AttachmentKind`] predicates
    ///   ([`is_api_visible`](AttachmentKind::is_api_visible) +
    ///   [`renders_in_transcript`](AttachmentKind::renders_in_transcript)).
    /// - `Progress` — UI-only.
    /// - `Tombstone` — neither (filtered in normalization).
    pub fn visibility(&self) -> Visibility {
        match self {
            // Human-typed user input is always both API-visible and
            // UI-visible. Reminder-injected "meta" user content lives in
            // `Message::Attachment` with an appropriate `AttachmentKind`.
            Self::User(_) | Self::Assistant(_) | Self::ToolResult(_) => Visibility::BOTH,
            Self::System(_) => Visibility::API_ONLY,
            Self::Attachment(a) => Visibility {
                api: a.kind.is_api_visible(),
                ui: a.kind.renders_in_transcript(),
            },
            Self::Progress(_) => Visibility::UI_ONLY,
            Self::Tombstone(_) => Visibility::NEITHER,
        }
    }

    pub fn kind(&self) -> MessageKind {
        match self {
            Self::User(_) => MessageKind::User,
            Self::Assistant(_) => MessageKind::Assistant,
            Self::System(_) => MessageKind::System,
            Self::Attachment(_) => MessageKind::Attachment,
            Self::ToolResult(_) => MessageKind::ToolResult,
            Self::Progress(_) => MessageKind::Progress,
            Self::Tombstone(_) => MessageKind::Tombstone,
        }
    }
}

#[cfg_attr(feature = "schema", derive(schemars::JsonSchema))]
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UserMessage {
    /// LLM API layer — sent to API directly via .message field.
    pub message: LlmMessage,
    pub uuid: Uuid,
    #[serde(default)]
    pub timestamp: String,
    #[serde(default)]
    pub is_visible_in_transcript_only: bool,
    /// Not sent to API.
    #[serde(default)]
    pub is_virtual: bool,
    #[serde(default)]
    pub is_compact_summary: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub permission_mode: Option<PermissionMode>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub origin: Option<MessageOrigin>,
    /// Parent tool-use id when this message was produced by a tool
    /// call's `new_messages` (e.g. inline skill expansion). Used by
    /// transcript grouping + as a marker that the message is
    /// transient until its parent tool_result resolves.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub parent_tool_use_id: Option<String>,
}

#[cfg_attr(feature = "schema", derive(schemars::JsonSchema))]
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AssistantMessage {
    pub message: LlmMessage,
    pub uuid: Uuid,
    #[serde(default)]
    pub model: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub stop_reason: Option<StopReason>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub usage: Option<TokenUsage>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cost_usd: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub request_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub api_error: Option<ApiError>,
}

/// Canonical typed stop reason — re-exported from `coco-inference`'s
/// extended `StopReason` (the single source of truth at the
/// vercel-ai-provider seam). 8 variants; see
/// `vercel-ai/provider/src/language_model/v4/finish_reason.rs` for
/// the multi-LLM mapping table.
pub use coco_llm_types::StopReason;

/// API error attached to an assistant message.
#[cfg_attr(feature = "schema", derive(schemars::JsonSchema))]
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ApiError {
    pub message: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub status_code: Option<i32>,
}

/// Attachment message: `kind` carries the TS-parity discriminant (60 variants),
/// `body` carries the typed payload.
///
/// **Invariant**: `kind` and `body` must agree — e.g. `kind = HookCancelled`
/// must come with `body = Silent(SilentPayload::HookCancelled(..))`. Do **not**
/// construct via struct literal; use the typed constructor helpers below.
#[cfg_attr(feature = "schema", derive(schemars::JsonSchema))]
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AttachmentMessage {
    pub uuid: Uuid,
    pub kind: AttachmentKind,
    pub body: AttachmentBody,
    /// Typed structured side data carried alongside an API-visible body.
    /// `None` for the overwhelming majority of attachments; populated by
    /// kinds whose model-visible prompt is derived from richer structured
    /// data the transcript / SDK / telemetry layers want to keep
    /// (currently only `skill_discovery`).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extras: Option<AttachmentExtras>,
}

impl AttachmentMessage {
    /// Build an API-bound attachment (body is a pre-rendered `LlmMessage`).
    ///
    /// Covers reminder-produced text (in-crate) and outside-reminder text
    /// re-injections (compact / plan file reference). Caller picks the
    /// `kind`; `debug_assert` rejects kinds whose coverage is explicitly
    /// not API-visible.
    pub fn api(kind: AttachmentKind, message: LlmMessage) -> Self {
        debug_assert!(
            kind.is_api_visible(),
            "AttachmentMessage::api called with non-API-visible kind {kind:?}",
        );
        Self {
            uuid: Uuid::new_v4(),
            kind,
            body: AttachmentBody::Api(message),
            extras: None,
        }
    }

    /// Build a unit attachment for feature-gated / runtime-bookkeeping kinds
    /// (no payload data).
    pub fn unit(kind: AttachmentKind) -> Self {
        debug_assert!(
            matches!(
                kind.coverage(),
                crate::Coverage::FeatureGated { .. } | crate::Coverage::RuntimeBookkeeping { .. }
            ),
            "AttachmentMessage::unit called with non-unit kind {kind:?}"
        );
        Self {
            uuid: Uuid::new_v4(),
            kind,
            body: AttachmentBody::Unit,
            extras: None,
        }
    }

    // ── Silent constructors (one per SilentPayload variant) ──
    // Pattern: kind is fixed per helper, payload type-enforced.

    pub fn silent_hook_cancelled(payload: HookCancelledPayload) -> Self {
        Self::silent(
            AttachmentKind::HookCancelled,
            SilentPayload::HookCancelled(payload),
        )
    }
    pub fn silent_hook_error_during_execution(payload: HookErrorDuringExecutionPayload) -> Self {
        Self::silent(
            AttachmentKind::HookErrorDuringExecution,
            SilentPayload::HookErrorDuringExecution(payload),
        )
    }
    pub fn silent_hook_non_blocking_error(payload: HookNonBlockingErrorPayload) -> Self {
        Self::silent(
            AttachmentKind::HookNonBlockingError,
            SilentPayload::HookNonBlockingError(payload),
        )
    }
    pub fn silent_hook_system_message(payload: HookSystemMessagePayload) -> Self {
        Self::silent(
            AttachmentKind::HookSystemMessage,
            SilentPayload::HookSystemMessage(payload),
        )
    }
    pub fn silent_hook_permission_decision(payload: HookPermissionDecisionPayload) -> Self {
        Self::silent(
            AttachmentKind::HookPermissionDecision,
            SilentPayload::HookPermissionDecision(payload),
        )
    }
    pub fn silent_command_permissions(payload: CommandPermissionsPayload) -> Self {
        Self::silent(
            AttachmentKind::CommandPermissions,
            SilentPayload::CommandPermissions(payload),
        )
    }
    pub fn silent_structured_output(payload: StructuredOutputPayload) -> Self {
        Self::silent(
            AttachmentKind::StructuredOutput,
            SilentPayload::StructuredOutput(payload),
        )
    }
    pub fn silent_dynamic_skill(payload: DynamicSkillPayload) -> Self {
        Self::silent(
            AttachmentKind::DynamicSkill,
            SilentPayload::DynamicSkill(payload),
        )
    }
    pub fn silent_max_turns_reached(payload: MaxTurnsReachedPayload) -> Self {
        Self::silent(
            AttachmentKind::MaxTurnsReached,
            SilentPayload::MaxTurnsReached(payload),
        )
    }
    pub fn skill_discovery(payload: SkillDiscoveryPayload) -> Self {
        let content = render_skill_discovery_prompt(&payload);
        Self::skill_discovery_with_content(payload, content)
    }
    pub fn skill_discovery_with_content(
        payload: SkillDiscoveryPayload,
        content: impl Into<String>,
    ) -> Self {
        Self {
            uuid: Uuid::new_v4(),
            kind: AttachmentKind::SkillDiscovery,
            body: AttachmentBody::Api(LlmMessage::user_text(content.into())),
            extras: Some(AttachmentExtras::SkillDiscovery(payload)),
        }
    }
    pub fn silent_already_read_file(payload: AlreadyReadFilePayload) -> Self {
        Self::silent(
            AttachmentKind::AlreadyReadFile,
            SilentPayload::AlreadyReadFile(payload),
        )
    }
    pub fn silent_edited_image_file(payload: EditedImageFilePayload) -> Self {
        Self::silent(
            AttachmentKind::EditedImageFile,
            SilentPayload::EditedImageFile(payload),
        )
    }

    /// Internal — callers use the typed silent_* helpers above.
    fn silent(kind: AttachmentKind, payload: SilentPayload) -> Self {
        Self {
            uuid: Uuid::new_v4(),
            kind,
            body: AttachmentBody::Silent(payload),
            extras: None,
        }
    }

    /// API-bound `LlmMessage` if this attachment carries one.
    /// `Silent` / `Unit` bodies never reach the API.
    pub fn as_api_message(&self) -> Option<&LlmMessage> {
        match &self.body {
            AttachmentBody::Api(m) => Some(m),
            AttachmentBody::Silent(_) | AttachmentBody::Unit => None,
        }
    }

    /// UI-facing text rendering of this attachment.
    ///
    /// Used by transcript / log extraction helpers. Returns empty string
    /// for bodies that have no textual representation (structured silent
    /// payloads rely on dedicated renderers).
    pub fn as_text_for_display(&self) -> String {
        match &self.body {
            AttachmentBody::Api(m) => llm_message_text(m),
            AttachmentBody::Silent(_) | AttachmentBody::Unit => String::new(),
        }
    }
}

/// Maximum chars in the rendered `skill_discovery` user-message prompt.
///
/// Per-turn injection budget — bounds the body even when many high-relevance
/// skills match. Truncation ellipsizes; full payload is still preserved on the
/// typed `SkillDiscoveryPayload` for any consumer that wants structured data.
pub const MAX_SKILL_DISCOVERY_RENDERED_CHARS: usize = 4000;

/// Render the user-visible prompt body for a `skill_discovery` attachment.
///
/// TS parity: `utils/messages.ts:3509-3515` — same template ("Skills relevant
/// to your task: …Invoke via Skill(\"<name>\") for complete instructions.").
/// Single canonical implementation so `AttachmentMessage::skill_discovery`
/// and `inject_reminders` produce byte-identical bodies.
pub fn render_skill_discovery_prompt(payload: &SkillDiscoveryPayload) -> String {
    let lines = payload
        .skills
        .iter()
        .map(|s| format!("- {}: {}", s.name, s.description))
        .collect::<Vec<_>>()
        .join("\n");
    let rendered = format!(
        "Skills relevant to your task:\n\n{lines}\n\nThese skills encode project-specific conventions. Invoke via Skill(\"<name>\") for complete instructions."
    );
    truncate_rendered_prompt(&rendered)
}

fn truncate_rendered_prompt(s: &str) -> String {
    if s.chars().count() <= MAX_SKILL_DISCOVERY_RENDERED_CHARS {
        return s.to_string();
    }
    let mut out = s
        .chars()
        .take(MAX_SKILL_DISCOVERY_RENDERED_CHARS.saturating_sub(3))
        .collect::<String>();
    out.push_str("...");
    out
}

/// Extract text content from an `LlmMessage` (simple concatenation of any
/// `TextContent` parts). Lives here so `AttachmentMessage::as_text_for_display`
/// can reuse it without pulling in `coco_messages`.
fn llm_message_text(msg: &LlmMessage) -> String {
    use super::aliases::AssistantContent;
    use super::aliases::LlmMessage as L;
    use super::aliases::UserContent;
    match msg {
        L::User { content, .. } => content
            .iter()
            .filter_map(|p| match p {
                UserContent::Text(t) => Some(t.text.as_str()),
                _ => None,
            })
            .collect::<Vec<_>>()
            .join(""),
        L::Assistant { content, .. } => content
            .iter()
            .filter_map(|p| match p {
                AssistantContent::Text(t) => Some(t.text.as_str()),
                _ => None,
            })
            .collect::<Vec<_>>()
            .join(""),
        _ => String::new(),
    }
}

#[cfg_attr(feature = "schema", derive(schemars::JsonSchema))]
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToolResultMessage {
    pub uuid: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub source_assistant_uuid: Option<Uuid>,
    pub message: LlmMessage,
    pub tool_use_id: String,
    pub tool_id: ToolId,
    #[serde(default)]
    pub is_error: bool,
}

#[cfg_attr(feature = "schema", derive(schemars::JsonSchema))]
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProgressMessage {
    pub tool_use_id: String,
    pub data: serde_json::Value,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub parent_message_uuid: Option<Uuid>,
}

#[cfg_attr(feature = "schema", derive(schemars::JsonSchema))]
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TombstoneMessage {
    pub uuid: Uuid,
    pub original_kind: MessageKind,
}

/// Which message variant was tombstoned.
#[cfg_attr(feature = "schema", derive(schemars::JsonSchema))]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum MessageKind {
    User,
    Assistant,
    System,
    Attachment,
    ToolResult,
    Progress,
    Tombstone,
}

/// System messages have sub-types for different notification kinds.
/// All system messages are `role: "user"` with `is_meta: true` for the API.
///
/// Wire discriminator is `kind`, matching the rest of the coco-rs
/// closed-set enums (`PermissionRule`, `ContentReplacementRecord`,
/// `event::*`). The semantic taxonomy (compact_boundary,
/// microcompact_boundary, …) matches TS `subtype:` values, but we
/// don't mirror the field name — see `coco-session::storage` doc for
/// the snake_case wire policy.
#[cfg_attr(feature = "schema", derive(schemars::JsonSchema))]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum SystemMessage {
    Informational(SystemInformationalMessage),
    ApiError(SystemApiErrorMessage),
    CompactBoundary(SystemCompactBoundaryMessage),
    MicrocompactBoundary(SystemMicrocompactBoundaryMessage),
    LocalCommand(SystemLocalCommandMessage),
    PermissionRetry(SystemPermissionRetryMessage),
    BridgeStatus(SystemBridgeStatusMessage),
    MemorySaved(SystemMemorySavedMessage),
    AwaySummary(SystemAwaySummaryMessage),
    AgentsKilled(SystemAgentsKilledMessage),
    ApiMetrics(SystemApiMetricsMessage),
    StopHookSummary(SystemStopHookSummaryMessage),
    TurnDuration(SystemTurnDurationMessage),
    ScheduledTaskFire(SystemScheduledTaskFireMessage),
    /// User cancellation marker. Replaces the legacy text-based
    /// `INTERRUPT_MESSAGE` / `INTERRUPT_MESSAGE_FOR_TOOL_USE` User
    /// messages with a typed variant. `for_tool_use` is computed once
    /// by the engine cancel finalizer and never recomputed downstream;
    /// see `engine-tui-unified-transcript-plan.md` §7.1.
    UserInterruption(SystemUserInterruptionMessage),
}

impl SystemMessage {
    pub fn uuid(&self) -> &Uuid {
        match self {
            Self::Informational(m) => &m.uuid,
            Self::ApiError(m) => &m.uuid,
            Self::CompactBoundary(m) => &m.uuid,
            Self::MicrocompactBoundary(m) => &m.uuid,
            Self::LocalCommand(m) => &m.uuid,
            Self::PermissionRetry(m) => &m.uuid,
            Self::BridgeStatus(m) => &m.uuid,
            Self::MemorySaved(m) => &m.uuid,
            Self::AwaySummary(m) => &m.uuid,
            Self::AgentsKilled(m) => &m.uuid,
            Self::ApiMetrics(m) => &m.uuid,
            Self::StopHookSummary(m) => &m.uuid,
            Self::TurnDuration(m) => &m.uuid,
            Self::ScheduledTaskFire(m) => &m.uuid,
            Self::UserInterruption(m) => &m.uuid,
        }
    }
}

#[cfg_attr(feature = "schema", derive(schemars::JsonSchema))]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum SystemMessageLevel {
    Info,
    Warning,
    Error,
}

#[cfg_attr(feature = "schema", derive(schemars::JsonSchema))]
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SystemInformationalMessage {
    pub uuid: Uuid,
    pub level: SystemMessageLevel,
    pub title: String,
    pub message: String,
}

#[cfg_attr(feature = "schema", derive(schemars::JsonSchema))]
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SystemApiErrorMessage {
    pub uuid: Uuid,
    pub error: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub status_code: Option<i32>,
}

/// Preserved message segment after partial compaction.
#[cfg_attr(feature = "schema", derive(schemars::JsonSchema))]
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PreservedSegment {
    /// First kept message UUID.
    pub head_uuid: Uuid,
    /// Summary or boundary anchor UUID.
    pub anchor_uuid: Uuid,
    /// Last kept message UUID.
    pub tail_uuid: Uuid,
}

#[cfg_attr(feature = "schema", derive(schemars::JsonSchema))]
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SystemCompactBoundaryMessage {
    pub uuid: Uuid,
    pub tokens_before: i64,
    pub tokens_after: i64,
    /// How compaction was triggered.
    #[serde(default = "default_compact_trigger")]
    pub trigger: CompactTrigger,
    /// User-supplied context for the compaction.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub user_context: Option<String>,
    /// Number of messages that were summarized.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub messages_summarized: Option<i32>,
    /// Tools discovered before compaction (for delta re-announcement).
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub pre_compact_discovered_tools: Vec<String>,
    /// Preserved segment for partial/suffix-preserving compaction.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub preserved_segment: Option<PreservedSegment>,
}

fn default_compact_trigger() -> CompactTrigger {
    CompactTrigger::Auto
}

/// Micro-compaction boundary marker.
///
/// Reserved for future use. coco-rs aligns with TS: micro-compaction
/// (client-side tool-result clearing + time-based MC) does NOT emit a
/// user-visible boundary message — it broadcasts a `ContextCompacted`
/// event with `trigger=TimeBased`/`Auto` instead, and the TUI renders
/// a transient toast (`toast.micro_compaction`) rather than persisting
/// a boundary in the transcript. The variant stays defined so wire
/// transcripts that include one (e.g. cached-microcompact builds) can
/// be parsed without errors.
#[cfg_attr(feature = "schema", derive(schemars::JsonSchema))]
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SystemMicrocompactBoundaryMessage {
    pub uuid: Uuid,
}

#[cfg_attr(feature = "schema", derive(schemars::JsonSchema))]
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SystemLocalCommandMessage {
    pub uuid: Uuid,
    pub command: String,
    pub output: String,
}

#[cfg_attr(feature = "schema", derive(schemars::JsonSchema))]
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SystemPermissionRetryMessage {
    pub uuid: Uuid,
    pub tool_name: String,
    pub message: String,
}

#[cfg_attr(feature = "schema", derive(schemars::JsonSchema))]
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SystemBridgeStatusMessage {
    pub uuid: Uuid,
    pub connected: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
}

/// Surfaced to the user's transcript when the auto-memory subsystem
/// has just landed new memory writes. TS parity:
/// `utils/messages.ts::createMemorySavedMessage(writtenPaths)` +
/// `services/autoDream/autoDream.ts:244-247` (which overrides
/// `verb` to `"Improved"` for dream consolidations vs. the default
/// `"Saved"` for extract).
#[cfg_attr(feature = "schema", derive(schemars::JsonSchema))]
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SystemMemorySavedMessage {
    pub uuid: Uuid,
    /// Paths the subagent wrote (or improved). TS `writtenPaths`. Excludes
    /// `MEMORY.md` — the index file is mechanical and not user-relevant.
    #[serde(default)]
    pub written_paths: Vec<String>,
    /// Display verb. `"Saved"` for extract; `"Improved"` for auto-dream
    /// consolidation. `#[serde(default)]` accepts older transcripts
    /// produced before this field was added.
    #[serde(default = "default_memory_saved_verb")]
    pub verb: String,
}

fn default_memory_saved_verb() -> String {
    "Saved".to_string()
}

#[cfg_attr(feature = "schema", derive(schemars::JsonSchema))]
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SystemAwaySummaryMessage {
    pub uuid: Uuid,
    pub summary: String,
}

#[cfg_attr(feature = "schema", derive(schemars::JsonSchema))]
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SystemAgentsKilledMessage {
    pub uuid: Uuid,
    pub count: i32,
}

#[cfg_attr(feature = "schema", derive(schemars::JsonSchema))]
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SystemApiMetricsMessage {
    pub uuid: Uuid,
    pub usage: TokenUsage,
    pub model: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cost_usd: Option<f64>,
}

#[cfg_attr(feature = "schema", derive(schemars::JsonSchema))]
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SystemStopHookSummaryMessage {
    pub uuid: Uuid,
    pub hook_name: String,
    pub outcome: String,
}

#[cfg_attr(feature = "schema", derive(schemars::JsonSchema))]
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SystemTurnDurationMessage {
    pub uuid: Uuid,
    pub duration_ms: i64,
}

#[cfg_attr(feature = "schema", derive(schemars::JsonSchema))]
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SystemScheduledTaskFireMessage {
    pub uuid: Uuid,
    pub task_id: String,
    pub schedule: String,
}

/// Authoritative cancel marker. `for_tool_use` is computed by the engine
/// cancel finalizer (which sees the in-flight tool-call state) and stored
/// here; every other consumer reads the field. This eliminates the
/// engine ↔ TUI recomputation race that the legacy text-based interrupt
/// markers exhibited.
#[cfg_attr(feature = "schema", derive(schemars::JsonSchema))]
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SystemUserInterruptionMessage {
    pub uuid: Uuid,
    pub for_tool_use: bool,
}

/// Where a message originated.
#[cfg_attr(feature = "schema", derive(schemars::JsonSchema))]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum MessageOrigin {
    UserInput,
    SystemInjected,
    ToolResult,
    CompactSummary,
    SubagentReply,
}

/// Direction hint for partial compaction.
#[cfg_attr(feature = "schema", derive(schemars::JsonSchema))]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum PartialCompactDirection {
    Oldest,
    Newest,
}

#[cfg(test)]
#[path = "message.test.rs"]
mod tests;
