//! Language model V4 generated file type.

use crate::shared::FileRawData;
use crate::shared::ProviderMetadata;
use serde::Deserialize;
use serde::Serialize;

/// Generated file data — either raw bytes/base64 or a URL.
///
/// Matches the 2-arm `SharedV4FileDataData | SharedV4FileDataUrl` tagged union
/// from the TypeScript v4 spec.
#[cfg_attr(feature = "schema", derive(schemars::JsonSchema))]
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "lowercase")]
pub enum LanguageModelV4FileData {
    /// Raw bytes (Uint8Array) or base64-encoded string.
    Data {
        /// The raw data.
        data: FileRawData,
    },
    /// A URL that points to the file.
    Url {
        /// The URL string.
        url: String,
    },
}

impl LanguageModelV4FileData {
    /// Create from base64 string.
    pub fn base64(data: impl Into<String>) -> Self {
        Self::Data {
            data: FileRawData::Base64(data.into()),
        }
    }

    /// Create from raw bytes.
    pub fn bytes(bytes: Vec<u8>) -> Self {
        Self::Data {
            data: FileRawData::Bytes(bytes),
        }
    }

    /// Create from a URL.
    pub fn url(url: impl Into<String>) -> Self {
        Self::Url { url: url.into() }
    }

    /// Return the inner `FileRawData` if this is a `Data` variant.
    pub fn as_data(&self) -> Option<&FileRawData> {
        match self {
            Self::Data { data } => Some(data),
            _ => None,
        }
    }

    /// Return the URL string if this is a `Url` variant.
    pub fn as_url(&self) -> Option<&str> {
        match self {
            Self::Url { url } => Some(url),
            _ => None,
        }
    }
}

/// A file generated by the language model.
///
/// The file data should be returned without any unnecessary conversion.
/// If the API returns base64 encoded strings, the file data should be returned
/// as base64 encoded strings. If the API returns binary data, it should be
/// returned as binary data.
#[cfg_attr(feature = "schema", derive(schemars::JsonSchema))]
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct LanguageModelV4File {
    /// Either a full IANA media type (`type/subtype`, e.g. `image/png`) or
    /// just the top-level IANA segment (e.g. `image`, `audio`).
    pub media_type: String,
    /// Generated file data as a tagged discriminated union.
    pub data: LanguageModelV4FileData,
    /// Provider-specific metadata.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub provider_metadata: Option<ProviderMetadata>,
}

impl LanguageModelV4File {
    /// Create a new file with base64 data.
    pub fn new(media_type: impl Into<String>, data: impl Into<String>) -> Self {
        Self {
            media_type: media_type.into(),
            data: LanguageModelV4FileData::base64(data),
            provider_metadata: None,
        }
    }

    /// Create a file with binary data.
    pub fn from_bytes(media_type: impl Into<String>, bytes: Vec<u8>) -> Self {
        Self {
            media_type: media_type.into(),
            data: LanguageModelV4FileData::bytes(bytes),
            provider_metadata: None,
        }
    }

    /// Create a file from a URL.
    pub fn from_url(media_type: impl Into<String>, url: impl Into<String>) -> Self {
        Self {
            media_type: media_type.into(),
            data: LanguageModelV4FileData::url(url),
            provider_metadata: None,
        }
    }

    /// Add provider metadata.
    pub fn with_metadata(mut self, metadata: ProviderMetadata) -> Self {
        self.provider_metadata = Some(metadata);
        self
    }
}

#[cfg(test)]
#[path = "file.test.rs"]
mod tests;
