//! Language model V4 file content type.
//!
//! Generated files as base64 encoded strings or binary data.

use crate::shared::ProviderMetadata;
use serde::Deserialize;
use serde::Serialize;

/// File data content - either base64 string or bytes.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum FileData {
    /// Base64 encoded data.
    Base64(String),
    /// Binary data.
    Bytes(Vec<u8>),
}

impl FileData {
    /// Create from base64 string.
    pub fn base64(data: impl Into<String>) -> Self {
        Self::Base64(data.into())
    }

    /// Create from bytes.
    pub fn bytes(data: Vec<u8>) -> Self {
        Self::Bytes(data)
    }
}

impl Serialize for FileData {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        match self {
            Self::Base64(s) => serializer.serialize_str(s),
            Self::Bytes(b) => {
                // Serialize bytes as base64
                use base64::Engine as _;
                use base64::engine::general_purpose::STANDARD;
                serializer.serialize_str(&STANDARD.encode(b))
            }
        }
    }
}

impl<'de> Deserialize<'de> for FileData {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let s = String::deserialize(deserializer)?;
        Ok(Self::Base64(s))
    }
}

/// A file that has been generated by the model.
///
/// Generated files as base64 encoded strings or binary data.
/// The files should be returned without any unnecessary conversion.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct LanguageModelV4File {
    /// The IANA media type of the file, e.g. `image/png` or `audio/mp3`.
    pub media_type: String,
    /// Generated file data as base64 encoded strings or binary data.
    pub data: FileData,
    /// Provider-specific metadata.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub provider_metadata: Option<ProviderMetadata>,
}

impl LanguageModelV4File {
    /// Create a new file content with base64 data.
    pub fn new(media_type: impl Into<String>, data: impl Into<String>) -> Self {
        Self {
            media_type: media_type.into(),
            data: FileData::base64(data),
            provider_metadata: None,
        }
    }

    /// Create a file with binary data.
    pub fn from_bytes(media_type: impl Into<String>, bytes: Vec<u8>) -> Self {
        Self {
            media_type: media_type.into(),
            data: FileData::bytes(bytes),
            provider_metadata: None,
        }
    }

    /// Add provider metadata.
    pub fn with_metadata(mut self, metadata: ProviderMetadata) -> Self {
        self.provider_metadata = Some(metadata);
        self
    }
}

#[cfg(test)]
#[path = "file.test.rs"]
mod tests;
