//! The keymap table. See `mod.rs` for the type model.
//!
//! New bindings are added here and only here. The three rendering layers
//! (`/help`, help overlay, JSON export) all read from this slice.

use coco_keybindings::KeybindingAction;

use super::KeymapBinding;
use super::KeymapEntry;
use super::KeymapGroup;

/// Convenience for `KeymapBinding::Verb { id: ... }`.
const fn verb(id: &'static str) -> KeymapBinding {
    KeymapBinding::Verb { id }
}

/// Convenience for `KeymapBinding::Action { action: ... }`.
const fn action(a: KeybindingAction) -> KeymapBinding {
    KeymapBinding::Action { action: a }
}

pub const KEYMAP: &[KeymapEntry] = &[
    // ───────────── Input bar — cursor movement & history ─────────────
    KeymapEntry {
        id: "input:cursor_home",
        combo: "Ctrl+A",
        alternates: &["Home"],
        group: KeymapGroup::InputCursor,
        binding: verb("cursor_home"),
        description_key: "keymap.input.cursor_home",
    },
    KeymapEntry {
        id: "input:cursor_end",
        combo: "Ctrl+E",
        alternates: &["End"],
        group: KeymapGroup::InputCursor,
        binding: verb("cursor_end"),
        description_key: "keymap.input.cursor_end",
    },
    KeymapEntry {
        id: "input:cursor_left",
        combo: "Ctrl+B",
        alternates: &["←"],
        group: KeymapGroup::InputCursor,
        binding: verb("cursor_left"),
        description_key: "keymap.input.cursor_left",
    },
    KeymapEntry {
        id: "input:cursor_right",
        combo: "Ctrl+F",
        alternates: &["→"],
        group: KeymapGroup::InputCursor,
        binding: verb("cursor_right"),
        description_key: "keymap.input.cursor_right",
    },
    KeymapEntry {
        id: "input:word_left",
        combo: "Alt+B",
        alternates: &["Ctrl+←"],
        group: KeymapGroup::InputCursor,
        binding: verb("word_left"),
        description_key: "keymap.input.word_left",
    },
    KeymapEntry {
        id: "input:word_right",
        combo: "Alt+F",
        alternates: &["Ctrl+→"],
        group: KeymapGroup::InputCursor,
        binding: verb("word_right"),
        description_key: "keymap.input.word_right",
    },
    KeymapEntry {
        id: "input:history",
        combo: "↑",
        alternates: &["↓"],
        group: KeymapGroup::InputCursor,
        binding: verb("history"),
        description_key: "keymap.input.history",
    },
    // ─────────────────── Input bar — text editing ────────────────────
    KeymapEntry {
        id: "input:delete_backward",
        combo: "Backspace",
        alternates: &["Ctrl+H"],
        group: KeymapGroup::InputEdit,
        binding: verb("delete_backward"),
        description_key: "keymap.input.delete_backward",
    },
    KeymapEntry {
        id: "input:delete_forward",
        combo: "Delete",
        alternates: &[],
        group: KeymapGroup::InputEdit,
        binding: verb("delete_forward"),
        description_key: "keymap.input.delete_forward",
    },
    KeymapEntry {
        id: "input:delete_word_backward",
        combo: "Ctrl+W",
        alternates: &["Alt+Backspace", "Ctrl+Backspace"],
        group: KeymapGroup::InputEdit,
        binding: verb("delete_word_backward"),
        description_key: "keymap.input.delete_word_backward",
    },
    KeymapEntry {
        id: "input:delete_word_forward",
        combo: "Ctrl+Delete",
        alternates: &[],
        group: KeymapGroup::InputEdit,
        binding: verb("delete_word_forward"),
        description_key: "keymap.input.delete_word_forward",
    },
    KeymapEntry {
        id: "input:kill_to_eol",
        combo: "Ctrl+K",
        alternates: &[],
        group: KeymapGroup::InputEdit,
        binding: verb("kill_to_end_of_line"),
        description_key: "keymap.input.kill_to_eol",
    },
    KeymapEntry {
        id: "input:kill_to_bol",
        combo: "Ctrl+U",
        alternates: &[],
        group: KeymapGroup::InputEdit,
        binding: verb("kill_to_beginning_of_line"),
        description_key: "keymap.input.kill_to_bol",
    },
    KeymapEntry {
        id: "input:yank",
        combo: "Ctrl+Y",
        alternates: &[],
        group: KeymapGroup::InputEdit,
        binding: verb("yank"),
        description_key: "keymap.input.yank",
    },
    KeymapEntry {
        id: "input:newline",
        combo: "Shift+Enter",
        alternates: &["Alt+Enter", "Ctrl+J"],
        group: KeymapGroup::InputEdit,
        binding: verb("insert_newline"),
        description_key: "keymap.input.newline",
    },
    KeymapEntry {
        id: "input:escape_newline",
        combo: "\\ + Enter",
        alternates: &[],
        group: KeymapGroup::InputEdit,
        binding: KeymapBinding::Marker,
        description_key: "keymap.input.escape_newline",
    },
    // ────────────── Input bar — submission / cancellation ────────────
    KeymapEntry {
        id: "input:submit",
        combo: "Enter",
        alternates: &[],
        group: KeymapGroup::InputSubmit,
        binding: verb("submit_input"),
        description_key: "keymap.input.submit",
    },
    KeymapEntry {
        id: "input:cancel",
        combo: "Esc",
        alternates: &[],
        group: KeymapGroup::InputSubmit,
        binding: verb("cancel"),
        description_key: "keymap.input.cancel",
    },
    KeymapEntry {
        id: "input:clear_input",
        combo: "Esc Esc",
        alternates: &[],
        group: KeymapGroup::InputSubmit,
        binding: KeymapBinding::Marker,
        description_key: "keymap.input.clear_input",
    },
    KeymapEntry {
        id: "input:interrupt",
        combo: "Ctrl+C",
        alternates: &[],
        group: KeymapGroup::InputSubmit,
        binding: action(KeybindingAction::AppInterrupt),
        description_key: "keymap.input.interrupt",
    },
    KeymapEntry {
        id: "input:exit",
        combo: "Ctrl+D",
        alternates: &[],
        group: KeymapGroup::InputSubmit,
        binding: action(KeybindingAction::AppExit),
        description_key: "keymap.input.exit",
    },
    KeymapEntry {
        id: "input:external_editor",
        combo: "Ctrl+G",
        alternates: &["Ctrl+X Ctrl+E"],
        group: KeymapGroup::InputSubmit,
        binding: action(KeybindingAction::ChatExternalEditor),
        description_key: "keymap.input.external_editor",
    },
    // ─────────────────────── Global hotkeys ──────────────────────────
    KeymapEntry {
        id: "global:cycle_permission_mode",
        combo: "Shift+Tab",
        alternates: &[],
        group: KeymapGroup::GlobalHotkey,
        binding: action(KeybindingAction::ChatCycleMode),
        description_key: "keymap.global.cycle_permission_mode",
    },
    KeymapEntry {
        id: "global:cycle_thinking",
        combo: "Ctrl+T",
        alternates: &[],
        group: KeymapGroup::GlobalHotkey,
        binding: action(KeybindingAction::ChatCycleThinking),
        description_key: "keymap.global.cycle_thinking",
    },
    KeymapEntry {
        id: "global:toggle_thinking",
        combo: "F2",
        alternates: &[],
        group: KeymapGroup::GlobalHotkey,
        binding: action(KeybindingAction::ChatThinkingToggle),
        description_key: "keymap.global.toggle_thinking",
    },
    KeymapEntry {
        id: "global:clear_screen",
        combo: "Ctrl+L",
        alternates: &[],
        group: KeymapGroup::GlobalHotkey,
        binding: action(KeybindingAction::AppRedraw),
        description_key: "keymap.global.clear_screen",
    },
    KeymapEntry {
        id: "global:history_search",
        combo: "Ctrl+R",
        alternates: &[],
        group: KeymapGroup::GlobalHotkey,
        binding: action(KeybindingAction::HistorySearch),
        description_key: "keymap.global.history_search",
    },
    KeymapEntry {
        id: "global:toggle_transcript",
        combo: "Ctrl+O",
        alternates: &[],
        group: KeymapGroup::GlobalHotkey,
        binding: action(KeybindingAction::AppToggleTranscript),
        description_key: "keymap.global.toggle_transcript",
    },
    KeymapEntry {
        id: "global:command_palette",
        combo: "Ctrl+P",
        alternates: &[],
        group: KeymapGroup::GlobalHotkey,
        binding: action(KeybindingAction::AppQuickOpen),
        description_key: "keymap.global.command_palette",
    },
    KeymapEntry {
        id: "global:stash",
        combo: "Ctrl+S",
        alternates: &[],
        group: KeymapGroup::GlobalHotkey,
        binding: action(KeybindingAction::ChatStash),
        description_key: "keymap.global.stash",
    },
    KeymapEntry {
        id: "global:kill_agents",
        combo: "Ctrl+X Ctrl+K",
        alternates: &[],
        group: KeymapGroup::GlobalHotkey,
        binding: action(KeybindingAction::ChatKillAgents),
        description_key: "keymap.global.kill_agents",
    },
    KeymapEntry {
        id: "global:quit",
        combo: "Ctrl+Q",
        alternates: &[],
        group: KeymapGroup::GlobalHotkey,
        binding: verb("quit"),
        description_key: "keymap.global.quit",
    },
    KeymapEntry {
        id: "global:help_overlay",
        combo: "F1",
        alternates: &["?"],
        group: KeymapGroup::GlobalHotkey,
        binding: KeymapBinding::Marker,
        description_key: "keymap.global.help_overlay",
    },
    // ────────────────────── Prompt prefixes ──────────────────────────
    KeymapEntry {
        id: "prefix:bash",
        combo: "!cmd",
        alternates: &[],
        group: KeymapGroup::PromptPrefix,
        binding: KeymapBinding::Marker,
        description_key: "keymap.prefix.bash",
    },
    KeymapEntry {
        id: "prefix:memory",
        combo: "#note",
        alternates: &[],
        group: KeymapGroup::PromptPrefix,
        binding: KeymapBinding::Marker,
        description_key: "keymap.prefix.memory",
    },
    KeymapEntry {
        id: "prefix:file",
        combo: "@path",
        alternates: &[],
        group: KeymapGroup::PromptPrefix,
        binding: KeymapBinding::Marker,
        description_key: "keymap.prefix.file",
    },
    KeymapEntry {
        id: "prefix:slash",
        combo: "/cmd",
        alternates: &[],
        group: KeymapGroup::PromptPrefix,
        binding: KeymapBinding::Marker,
        description_key: "keymap.prefix.slash",
    },
    // ────────────────────── Vim Normal mode ──────────────────────────
    KeymapEntry {
        id: "vim:insert_modes",
        combo: "i / I / a / A",
        alternates: &[],
        group: KeymapGroup::VimNormal,
        binding: KeymapBinding::Marker,
        description_key: "keymap.vim.insert",
    },
    KeymapEntry {
        id: "vim:open_line",
        combo: "o / O",
        alternates: &[],
        group: KeymapGroup::VimNormal,
        binding: KeymapBinding::Marker,
        description_key: "keymap.vim.open_line",
    },
    KeymapEntry {
        id: "vim:move",
        combo: "h / l / w / b / e",
        alternates: &[],
        group: KeymapGroup::VimNormal,
        binding: KeymapBinding::Marker,
        description_key: "keymap.vim.move",
    },
    KeymapEntry {
        id: "vim:line_anchor",
        combo: "0 / ^ / $",
        alternates: &[],
        group: KeymapGroup::VimNormal,
        binding: KeymapBinding::Marker,
        description_key: "keymap.vim.line_anchor",
    },
    KeymapEntry {
        id: "vim:jump",
        combo: "gg / G",
        alternates: &[],
        group: KeymapGroup::VimNormal,
        binding: KeymapBinding::Marker,
        description_key: "keymap.vim.jump",
    },
    KeymapEntry {
        id: "vim:delete_replace",
        combo: "x / r<x>",
        alternates: &[],
        group: KeymapGroup::VimNormal,
        binding: KeymapBinding::Marker,
        description_key: "keymap.vim.delete_replace",
    },
    KeymapEntry {
        id: "vim:line_ops",
        combo: "dd / cc / yy",
        alternates: &[],
        group: KeymapGroup::VimNormal,
        binding: KeymapBinding::Marker,
        description_key: "keymap.vim.line_ops",
    },
    KeymapEntry {
        id: "vim:operator_motion",
        combo: "dw / cw / yw / d$ / c$",
        alternates: &[],
        group: KeymapGroup::VimNormal,
        binding: KeymapBinding::Marker,
        description_key: "keymap.vim.operator_motion",
    },
    KeymapEntry {
        id: "vim:text_object",
        combo: "diw / daw / di\" / di(",
        alternates: &[],
        group: KeymapGroup::VimNormal,
        binding: KeymapBinding::Marker,
        description_key: "keymap.vim.text_object",
    },
    KeymapEntry {
        id: "vim:put",
        combo: "p / P",
        alternates: &[],
        group: KeymapGroup::VimNormal,
        binding: KeymapBinding::Marker,
        description_key: "keymap.vim.put",
    },
    KeymapEntry {
        id: "vim:find",
        combo: "f<x> / F<x> / t<x> / T<x> / ; / ,",
        alternates: &[],
        group: KeymapGroup::VimNormal,
        binding: KeymapBinding::Marker,
        description_key: "keymap.vim.find",
    },
    KeymapEntry {
        id: "vim:undo_repeat",
        combo: "u / .",
        alternates: &[],
        group: KeymapGroup::VimNormal,
        binding: KeymapBinding::Marker,
        description_key: "keymap.vim.undo_repeat",
    },
    KeymapEntry {
        id: "vim:normal_mode",
        combo: "Esc",
        alternates: &[],
        group: KeymapGroup::VimNormal,
        binding: KeymapBinding::Marker,
        description_key: "keymap.vim.normal_mode",
    },
];
