//! Default keybinding table.
//!
//! Provides the built-in bindings that match the current cocode-rs key
//! mappings. These are the bindings used when no user configuration file
//! exists or when `Feature::KeybindingCustomization` is disabled.

use crossterm::event::KeyCode;
use crossterm::event::KeyModifiers;

use crate::action::Action;
use crate::context::KeybindingContext;
use crate::key::KeyCombo;
use crate::key::KeySequence;
use crate::resolver::Binding;

/// Build a single-key binding.
fn bind(context: KeybindingContext, mods: KeyModifiers, code: KeyCode, action: Action) -> Binding {
    Binding {
        context,
        sequence: KeySequence::single(KeyCombo::new(mods, code)),
        action,
    }
}

const NONE: KeyModifiers = KeyModifiers::NONE;
const CTRL: KeyModifiers = KeyModifiers::CONTROL;
const SHIFT: KeyModifiers = KeyModifiers::SHIFT;
const ALT: KeyModifiers = KeyModifiers::ALT;

/// Returns the complete default binding table.
///
/// Order matters: user bindings are appended after these, and last-match-wins
/// semantics ensure user bindings override defaults.
pub fn default_bindings() -> Vec<Binding> {
    let ctrl_shift = CTRL.union(SHIFT);

    vec![
        // ========== Global Context ==========
        bind(
            KeybindingContext::Global,
            CTRL,
            KeyCode::Char('c'),
            Action::AppInterrupt,
        ),
        // NOTE: No single Esc here — it lives in Chat to allow the Esc-Esc chord to work.
        bind(
            KeybindingContext::Global,
            NONE,
            KeyCode::PageUp,
            Action::ExtPageUp,
        ),
        bind(
            KeybindingContext::Global,
            NONE,
            KeyCode::PageDown,
            Action::ExtPageDown,
        ),
        // History search (Ctrl+R in Global — entry point from any context)
        bind(
            KeybindingContext::Global,
            CTRL,
            KeyCode::Char('r'),
            Action::HistorySearch,
        ),
        // Paste (Global — works in all contexts including overlays)
        bind(
            KeybindingContext::Global,
            CTRL,
            KeyCode::Char('v'),
            Action::ChatImagePaste,
        ),
        bind(
            KeybindingContext::Global,
            ALT,
            KeyCode::Char('v'),
            Action::ChatImagePaste,
        ),
        // ========== Chat Context ==========
        // Mode toggles
        bind(
            KeybindingContext::Chat,
            NONE,
            KeyCode::Tab,
            Action::ExtTogglePlanMode,
        ),
        bind(
            KeybindingContext::Chat,
            CTRL,
            KeyCode::Char('t'),
            Action::ExtCycleThinkingLevel,
        ),
        bind(
            KeybindingContext::Chat,
            CTRL,
            KeyCode::Char('m'),
            Action::ExtCycleModel,
        ),
        // Agent control
        bind(
            KeybindingContext::Chat,
            CTRL,
            KeyCode::Char('b'),
            Action::ExtBackgroundAllTasks,
        ),
        bind(
            KeybindingContext::Chat,
            CTRL,
            KeyCode::Char('f'),
            Action::ChatKillAgents,
        ),
        // UI overlays
        bind(
            KeybindingContext::Chat,
            CTRL,
            KeyCode::Char('e'),
            Action::ChatExternalEditor,
        ),
        bind(
            KeybindingContext::Chat,
            CTRL,
            KeyCode::Char('g'),
            Action::ExtOpenPlanEditor,
        ),
        bind(
            KeybindingContext::Chat,
            CTRL,
            KeyCode::Char('p'),
            Action::ExtShowCommandPalette,
        ),
        bind(
            KeybindingContext::Chat,
            CTRL,
            KeyCode::Char('s'),
            Action::ExtShowSessionBrowser,
        ),
        bind(
            KeybindingContext::Chat,
            CTRL,
            KeyCode::Char('l'),
            Action::ExtClearScreen,
        ),
        bind(
            KeybindingContext::Chat,
            CTRL,
            KeyCode::Char('q'),
            Action::ExtQuit,
        ),
        bind(
            KeybindingContext::Chat,
            CTRL,
            KeyCode::Char('a'),
            Action::ExtSelectAll,
        ),
        // Display toggles (Ctrl+Shift)
        bind(
            KeybindingContext::Chat,
            ctrl_shift,
            KeyCode::Char('T'),
            Action::ExtToggleThinking,
        ),
        bind(
            KeybindingContext::Chat,
            ctrl_shift,
            KeyCode::Char('E'),
            Action::ExtToggleToolCollapse,
        ),
        bind(
            KeybindingContext::Chat,
            ctrl_shift,
            KeyCode::Char('R'),
            Action::ExtToggleSystemReminders,
        ),
        // Help
        bind(
            KeybindingContext::Chat,
            NONE,
            KeyCode::F(1),
            Action::ExtShowHelp,
        ),
        bind(
            KeybindingContext::Chat,
            SHIFT,
            KeyCode::Char('?'),
            Action::ExtShowHelp,
        ),
        // Submit / Newline
        bind(
            KeybindingContext::Chat,
            NONE,
            KeyCode::Enter,
            Action::ChatSubmit,
        ),
        bind(
            KeybindingContext::Chat,
            CTRL,
            KeyCode::Enter,
            Action::ChatSubmit,
        ),
        bind(
            KeybindingContext::Chat,
            SHIFT,
            KeyCode::Enter,
            Action::ExtInsertNewline,
        ),
        bind(
            KeybindingContext::Chat,
            ALT,
            KeyCode::Enter,
            Action::ExtInsertNewline,
        ),
        // Navigation
        bind(
            KeybindingContext::Chat,
            NONE,
            KeyCode::PageUp,
            Action::ExtPageUp,
        ),
        bind(
            KeybindingContext::Chat,
            NONE,
            KeyCode::PageDown,
            Action::ExtPageDown,
        ),
        bind(
            KeybindingContext::Chat,
            CTRL,
            KeyCode::Up,
            Action::ExtPageUp,
        ),
        bind(
            KeybindingContext::Chat,
            CTRL,
            KeyCode::Down,
            Action::ExtPageDown,
        ),
        bind(
            KeybindingContext::Chat,
            ALT,
            KeyCode::Up,
            Action::ExtScrollUp,
        ),
        bind(
            KeybindingContext::Chat,
            ALT,
            KeyCode::Down,
            Action::ExtScrollDown,
        ),
        // Editing: cursor movement
        bind(
            KeybindingContext::Chat,
            NONE,
            KeyCode::Left,
            Action::ExtCursorLeft,
        ),
        bind(
            KeybindingContext::Chat,
            NONE,
            KeyCode::Right,
            Action::ExtCursorRight,
        ),
        bind(
            KeybindingContext::Chat,
            NONE,
            KeyCode::Up,
            Action::ExtCursorUp,
        ),
        bind(
            KeybindingContext::Chat,
            NONE,
            KeyCode::Down,
            Action::ExtCursorDown,
        ),
        bind(
            KeybindingContext::Chat,
            NONE,
            KeyCode::Home,
            Action::ExtCursorHome,
        ),
        bind(
            KeybindingContext::Chat,
            NONE,
            KeyCode::End,
            Action::ExtCursorEnd,
        ),
        bind(
            KeybindingContext::Chat,
            CTRL,
            KeyCode::Left,
            Action::ExtWordLeft,
        ),
        bind(
            KeybindingContext::Chat,
            CTRL,
            KeyCode::Right,
            Action::ExtWordRight,
        ),
        // Editing: delete
        bind(
            KeybindingContext::Chat,
            NONE,
            KeyCode::Backspace,
            Action::ExtDeleteBackward,
        ),
        bind(
            KeybindingContext::Chat,
            CTRL,
            KeyCode::Backspace,
            Action::ExtDeleteWordBackward,
        ),
        bind(
            KeybindingContext::Chat,
            NONE,
            KeyCode::Delete,
            Action::ExtDeleteForward,
        ),
        bind(
            KeybindingContext::Chat,
            CTRL,
            KeyCode::Delete,
            Action::ExtDeleteWordForward,
        ),
        // Editing: Emacs-style kill buffer
        bind(
            KeybindingContext::Chat,
            CTRL,
            KeyCode::Char('k'),
            Action::ExtKillToEndOfLine,
        ),
        bind(
            KeybindingContext::Chat,
            CTRL,
            KeyCode::Char('y'),
            Action::ExtYank,
        ),
        // Cancel: single Esc (also serves as chord-cancel fallback)
        bind(
            KeybindingContext::Chat,
            NONE,
            KeyCode::Esc,
            Action::ChatCancel,
        ),
        // Rewind chord: Esc Esc (must come AFTER single Esc — chord prefix match takes priority)
        Binding {
            context: KeybindingContext::Chat,
            sequence: KeySequence {
                keys: vec![
                    KeyCombo::new(NONE, KeyCode::Esc),
                    KeyCombo::new(NONE, KeyCode::Esc),
                ],
            },
            action: Action::ExtShowRewindSelector,
        },
        // ========== Autocomplete Context ==========
        bind(
            KeybindingContext::Autocomplete,
            NONE,
            KeyCode::Up,
            Action::AutocompletePrevious,
        ),
        bind(
            KeybindingContext::Autocomplete,
            NONE,
            KeyCode::Down,
            Action::AutocompleteNext,
        ),
        bind(
            KeybindingContext::Autocomplete,
            NONE,
            KeyCode::Tab,
            Action::AutocompleteAccept,
        ),
        bind(
            KeybindingContext::Autocomplete,
            NONE,
            KeyCode::Enter,
            Action::AutocompleteAccept,
        ),
        bind(
            KeybindingContext::Autocomplete,
            NONE,
            KeyCode::Esc,
            Action::AutocompleteDismiss,
        ),
        // ========== Confirmation Context ==========
        bind(
            KeybindingContext::Confirmation,
            NONE,
            KeyCode::Char('y'),
            Action::ConfirmYes,
        ),
        bind(
            KeybindingContext::Confirmation,
            SHIFT,
            KeyCode::Char('Y'),
            Action::ConfirmYes,
        ),
        bind(
            KeybindingContext::Confirmation,
            NONE,
            KeyCode::Char('n'),
            Action::ConfirmNo,
        ),
        bind(
            KeybindingContext::Confirmation,
            SHIFT,
            KeyCode::Char('N'),
            Action::ConfirmNo,
        ),
        bind(
            KeybindingContext::Confirmation,
            CTRL,
            KeyCode::Char('a'),
            Action::ExtApproveAll,
        ),
        bind(
            KeybindingContext::Confirmation,
            NONE,
            KeyCode::Up,
            Action::ConfirmPrevious,
        ),
        bind(
            KeybindingContext::Confirmation,
            NONE,
            KeyCode::Char('k'),
            Action::ConfirmPrevious,
        ),
        bind(
            KeybindingContext::Confirmation,
            NONE,
            KeyCode::Down,
            Action::ConfirmNext,
        ),
        bind(
            KeybindingContext::Confirmation,
            NONE,
            KeyCode::Char('j'),
            Action::ConfirmNext,
        ),
        bind(
            KeybindingContext::Confirmation,
            NONE,
            KeyCode::Enter,
            Action::ConfirmYes,
        ),
        bind(
            KeybindingContext::Confirmation,
            NONE,
            KeyCode::Esc,
            Action::SelectCancel,
        ),
        bind(
            KeybindingContext::Confirmation,
            CTRL,
            KeyCode::Char('c'),
            Action::SelectCancel,
        ),
        // ========== Select Context ==========
        bind(
            KeybindingContext::Select,
            NONE,
            KeyCode::Up,
            Action::SelectPrevious,
        ),
        bind(
            KeybindingContext::Select,
            NONE,
            KeyCode::Down,
            Action::SelectNext,
        ),
        bind(
            KeybindingContext::Select,
            NONE,
            KeyCode::Enter,
            Action::SelectAccept,
        ),
        bind(
            KeybindingContext::Select,
            NONE,
            KeyCode::Esc,
            Action::SelectCancel,
        ),
        // ========== ModelPicker Context ==========
        bind(
            KeybindingContext::ModelPicker,
            NONE,
            KeyCode::Up,
            Action::ModelPickerPrevious,
        ),
        bind(
            KeybindingContext::ModelPicker,
            NONE,
            KeyCode::Down,
            Action::ModelPickerNext,
        ),
        bind(
            KeybindingContext::ModelPicker,
            NONE,
            KeyCode::Enter,
            Action::ModelPickerAccept,
        ),
        bind(
            KeybindingContext::ModelPicker,
            NONE,
            KeyCode::Esc,
            Action::ModelPickerCancel,
        ),
        // ========== Help Context ==========
        bind(
            KeybindingContext::Help,
            NONE,
            KeyCode::Esc,
            Action::HelpClose,
        ),
        bind(
            KeybindingContext::Help,
            NONE,
            KeyCode::Up,
            Action::HelpScrollUp,
        ),
        bind(
            KeybindingContext::Help,
            NONE,
            KeyCode::Down,
            Action::HelpScrollDown,
        ),
        // ========== Plugin Context ==========
        bind(
            KeybindingContext::Plugin,
            NONE,
            KeyCode::Tab,
            Action::PluginNextTab,
        ),
        bind(
            KeybindingContext::Plugin,
            NONE,
            KeyCode::BackTab,
            Action::PluginPreviousTab,
        ),
        bind(
            KeybindingContext::Plugin,
            NONE,
            KeyCode::Up,
            Action::PluginPrevious,
        ),
        bind(
            KeybindingContext::Plugin,
            NONE,
            KeyCode::Down,
            Action::PluginNext,
        ),
        bind(
            KeybindingContext::Plugin,
            NONE,
            KeyCode::Enter,
            Action::PluginAccept,
        ),
        bind(
            KeybindingContext::Plugin,
            NONE,
            KeyCode::Esc,
            Action::PluginClose,
        ),
        // ========== Task Context ==========
        bind(
            KeybindingContext::Task,
            CTRL,
            KeyCode::Char('b'),
            Action::TaskBackground,
        ),
        // ========== MessageSelector Context ==========
        bind(
            KeybindingContext::MessageSelector,
            NONE,
            KeyCode::Up,
            Action::MessageSelectorUp,
        ),
        bind(
            KeybindingContext::MessageSelector,
            NONE,
            KeyCode::Down,
            Action::MessageSelectorDown,
        ),
        bind(
            KeybindingContext::MessageSelector,
            NONE,
            KeyCode::Char('k'),
            Action::MessageSelectorUp,
        ),
        bind(
            KeybindingContext::MessageSelector,
            NONE,
            KeyCode::Char('j'),
            Action::MessageSelectorDown,
        ),
        bind(
            KeybindingContext::MessageSelector,
            CTRL,
            KeyCode::Up,
            Action::MessageSelectorTop,
        ),
        bind(
            KeybindingContext::MessageSelector,
            SHIFT,
            KeyCode::Up,
            Action::MessageSelectorTop,
        ),
        bind(
            KeybindingContext::MessageSelector,
            CTRL,
            KeyCode::Down,
            Action::MessageSelectorBottom,
        ),
        bind(
            KeybindingContext::MessageSelector,
            SHIFT,
            KeyCode::Down,
            Action::MessageSelectorBottom,
        ),
        bind(
            KeybindingContext::MessageSelector,
            SHIFT,
            KeyCode::Char('K'),
            Action::MessageSelectorTop,
        ),
        bind(
            KeybindingContext::MessageSelector,
            SHIFT,
            KeyCode::Char('J'),
            Action::MessageSelectorBottom,
        ),
        bind(
            KeybindingContext::MessageSelector,
            NONE,
            KeyCode::Enter,
            Action::MessageSelectorSelect,
        ),
        bind(
            KeybindingContext::MessageSelector,
            NONE,
            KeyCode::Esc,
            Action::MessageSelectorCancel,
        ),
        // ========== HistorySearch Context ==========
        bind(
            KeybindingContext::HistorySearch,
            CTRL,
            KeyCode::Char('r'),
            Action::HistorySearchNext,
        ),
        bind(
            KeybindingContext::HistorySearch,
            NONE,
            KeyCode::Esc,
            Action::HistorySearchAccept,
        ),
        bind(
            KeybindingContext::HistorySearch,
            NONE,
            KeyCode::Tab,
            Action::HistorySearchAccept,
        ),
        bind(
            KeybindingContext::HistorySearch,
            CTRL,
            KeyCode::Char('c'),
            Action::HistorySearchCancel,
        ),
        bind(
            KeybindingContext::HistorySearch,
            NONE,
            KeyCode::Enter,
            Action::HistorySearchExecute,
        ),
        // ========== DiffDialog Context ==========
        bind(
            KeybindingContext::DiffDialog,
            NONE,
            KeyCode::Esc,
            Action::DiffDismiss,
        ),
        bind(
            KeybindingContext::DiffDialog,
            NONE,
            KeyCode::Left,
            Action::DiffPreviousSource,
        ),
        bind(
            KeybindingContext::DiffDialog,
            NONE,
            KeyCode::Right,
            Action::DiffNextSource,
        ),
        bind(
            KeybindingContext::DiffDialog,
            NONE,
            KeyCode::Up,
            Action::DiffPreviousFile,
        ),
        bind(
            KeybindingContext::DiffDialog,
            NONE,
            KeyCode::Down,
            Action::DiffNextFile,
        ),
        bind(
            KeybindingContext::DiffDialog,
            NONE,
            KeyCode::Enter,
            Action::DiffViewDetails,
        ),
        // ========== Transcript Context ==========
        bind(
            KeybindingContext::Transcript,
            CTRL,
            KeyCode::Char('e'),
            Action::TranscriptToggleShowAll,
        ),
        bind(
            KeybindingContext::Transcript,
            CTRL,
            KeyCode::Char('c'),
            Action::TranscriptExit,
        ),
        bind(
            KeybindingContext::Transcript,
            NONE,
            KeyCode::Esc,
            Action::TranscriptExit,
        ),
    ]
}

#[cfg(test)]
#[path = "defaults.test.rs"]
mod tests;
