//! Prompt module.
//!
//! This module provides types and utilities for constructing prompts
//! for language model interactions.

mod call_settings;
mod content_part;
mod convert;
mod create_tool_model_output;
mod data_content;
mod message;
mod message_conversion_error;
mod prepare_call_settings;
mod prepare_tools_and_tool_choice;
mod standardize;
mod types;
mod wrap_gateway_error;

pub use call_settings::CallSettings;
pub use call_settings::TimeoutConfiguration;
pub use content_part::PromptContentItem;
pub use content_part::PromptFileData;
pub use content_part::PromptFilePart;
pub use content_part::PromptImageData;
pub use content_part::PromptImagePart;
pub use content_part::PromptReasoningPart;
pub use content_part::PromptTextPart;
pub use content_part::PromptToolCallPart;
pub use content_part::PromptToolResultOutput;
pub use content_part::PromptToolResultPart;
pub use convert::combine_tool_messages;
pub use convert::convert_to_language_model_message;
pub use convert::convert_to_language_model_prompt;
pub use create_tool_model_output::create_tool_result_content;
pub use create_tool_model_output::create_tool_result_part;
pub use create_tool_model_output::create_tool_result_part_from_error;
pub use create_tool_model_output::create_tool_result_part_from_image;
pub use create_tool_model_output::create_tool_result_part_from_text;
pub use data_content::DataContentValue;
pub use data_content::convert_to_language_model_data_content;
pub use data_content::convert_uint8_array_to_text;
pub use message::PromptAssistantContent;
pub use message::PromptAssistantContentPart;
pub use message::PromptAssistantMessage;
pub use message::PromptMessage;
pub use message::PromptSystemMessage;
pub use message::PromptToolContentPart;
pub use message::PromptToolMessage;
pub use message::PromptUserContent;
pub use message::PromptUserContentPart;
pub use message::PromptUserMessage;
pub use message_conversion_error::MessageConversionError;
pub use message_conversion_error::MessageConversionResult;
pub use prepare_call_settings::prepare_call_settings;
pub use prepare_call_settings::prepare_call_settings_with_defaults;
pub use prepare_tools_and_tool_choice::determine_tool_choice;
pub use prepare_tools_and_tool_choice::is_tool_call_disabled;
pub use prepare_tools_and_tool_choice::is_tool_call_required;
pub use prepare_tools_and_tool_choice::prepare_tool_definitions;
pub use prepare_tools_and_tool_choice::prepare_tools_and_tool_choice;
pub use standardize::StandardizedPrompt;
pub use standardize::standardize_messages_prompt;
pub use standardize::standardize_prompt;
pub use standardize::standardize_text_prompt;
pub use types::Prompt;
pub use types::PromptContent;
pub use types::SystemPrompt;
pub use wrap_gateway_error::get_user_friendly_message;
pub use wrap_gateway_error::is_gateway_error_retryable;
pub use wrap_gateway_error::wrap_gateway_error;
pub use wrap_gateway_error::wrap_gateway_error_with_context;
