mod background;
mod context;
mod definition;
pub mod definitions;
pub mod error;
mod filter;
pub mod identity;
mod loader;
mod manager;
pub mod signal;
mod spawn;
mod transcript;

pub use background::BackgroundAgent;
pub use context::ChildToolUseContext;
pub use context::filter_orphaned_tool_uses;
pub use definition::AgentDefinition;
pub use definition::AgentHookDefinition;
pub use definition::AgentSource;
pub use definition::IsolationMode;
pub use definition::McpServerRef;
pub use definition::MemoryScope;
pub use definitions::all_agents;
pub use definitions::builtin_agents;
pub use definitions::builtin_agents_with_config;
pub use definitions::builtin_agents_with_overrides;
pub use error::Result;
pub use error::SubagentError;
pub use filter::ToolFilterResult;
pub use filter::filter_tools_for_agent;
pub use identity::AgentIdentity;
pub use identity::CURRENT_AGENT;
pub use identity::current_agent;
pub use loader::load_custom_agents;
pub use loader::merge_custom_agents;
pub use manager::AgentExecuteFn;
pub use manager::AgentExecuteParams;
pub use manager::AgentInstance;
pub use manager::AgentInstanceInfo;
pub use manager::AgentStatus;
pub use manager::BackgroundOrigin;
pub use manager::BackgroundStopHookFn;
pub use manager::SpawnResult;
pub use manager::SubagentManager;
pub use signal::backgroundable_agent_ids;
pub use signal::is_agent_backgroundable;
pub use signal::register_backgroundable_agent;
pub use signal::trigger_background_transition;
pub use signal::unregister_backgroundable_agent;
pub use spawn::SpawnInput;
pub use transcript::TranscriptRecorder;
pub use transcript::read_from_offset;
