use std::path::Path;
use std::process::Command;

/// Branch prefix for agent worktrees.
const AGENT_WORKTREE_BRANCH_PREFIX: &str = "agent/task-";

/// An orphaned worktree discovered during cleanup.
#[derive(Debug)]
struct OrphanedWorktree {
    path: String,
    branch: String,
}

/// Clean up orphaned agent worktrees and their branches.
///
/// Scans for worktrees whose branches match the `agent/task-*` naming
/// convention (auto-generated by `EnterWorktree`), removes them, deletes
/// the associated branches, and prunes stale bookkeeping entries.
///
/// Returns the number of worktrees cleaned up.
pub fn cleanup_orphaned_worktrees(cwd: &Path) -> i32 {
    if !crate::is_inside_git_repo(cwd) {
        return 0;
    }

    let orphans = match list_orphaned_worktrees(cwd) {
        Some(v) => v,
        None => return 0,
    };

    let count = orphans.len() as i32;
    for orphan in &orphans {
        // Remove the worktree directory
        let _ = Command::new("git")
            .current_dir(cwd)
            .args(["worktree", "remove", "--force", &orphan.path])
            .output();

        // Delete the orphaned branch
        let _ = Command::new("git")
            .current_dir(cwd)
            .args(["branch", "-D", &orphan.branch])
            .output();
    }

    let _ = Command::new("git")
        .current_dir(cwd)
        .args(["worktree", "prune"])
        .output();

    count
}

/// Parse `git worktree list --porcelain` to find agent/task-* worktrees.
fn list_orphaned_worktrees(cwd: &Path) -> Option<Vec<OrphanedWorktree>> {
    let output = Command::new("git")
        .current_dir(cwd)
        .args(["worktree", "list", "--porcelain"])
        .output()
        .ok()?;

    if !output.status.success() {
        return None;
    }

    let text = String::from_utf8_lossy(&output.stdout);
    let mut orphans = Vec::new();
    let mut worktree_path: Option<String> = None;

    for line in text.lines() {
        if let Some(path) = line.strip_prefix("worktree ") {
            worktree_path = Some(path.to_string());
        } else if let Some(branch) = line.strip_prefix("branch refs/heads/") {
            if branch.starts_with(AGENT_WORKTREE_BRANCH_PREFIX)
                && let Some(wt_path) = worktree_path.take()
            {
                orphans.push(OrphanedWorktree {
                    path: wt_path,
                    branch: branch.to_string(),
                });
            }
            worktree_path = None;
        } else if line.is_empty() {
            worktree_path = None;
        }
    }

    Some(orphans)
}

#[cfg(test)]
#[path = "worktree.test.rs"]
mod tests;
