//! Unified provider error enum.
//!
//! Allows pattern matching on all provider error types.

use thiserror::Error;

use super::api_call_error::APICallError;
use super::empty_response_body_error::EmptyResponseBodyError;
use super::invalid_argument_error::InvalidArgumentError;
use super::invalid_prompt_error::InvalidPromptError;
use super::invalid_response_data_error::InvalidResponseDataError;
use super::json_parse_error::JSONParseError;
use super::load_api_key_error::LoadAPIKeyError;
use super::load_setting_error::LoadSettingError;
use super::no_content_generated_error::NoContentGeneratedError;
use super::no_such_model_error::NoSuchModelError;
use super::too_many_embedding_values_for_call_error::TooManyEmbeddingValuesForCallError;
use super::type_validation_error::TypeValidationError;
use super::unsupported_functionality_error::UnsupportedFunctionalityError;

/// Unified error type for all provider errors.
///
/// This enum allows pattern matching on specific error types
/// instead of relying on string-based error names.
#[non_exhaustive]
#[derive(Debug, Error)]
pub enum ProviderError {
    /// Error from an API call (network, HTTP status, etc.).
    #[error(transparent)]
    ApiCall(#[from] APICallError),
    /// The response body was empty when content was expected.
    #[error(transparent)]
    EmptyResponseBody(#[from] EmptyResponseBodyError),
    /// An invalid argument was provided.
    #[error(transparent)]
    InvalidArgument(#[from] InvalidArgumentError),
    /// The prompt was invalid.
    #[error(transparent)]
    InvalidPrompt(#[from] InvalidPromptError),
    /// The response data was invalid or couldn't be parsed.
    #[error(transparent)]
    InvalidResponseData(#[from] InvalidResponseDataError),
    /// JSON parsing failed.
    #[error(transparent)]
    JsonParse(#[from] JSONParseError),
    /// Failed to load an API key.
    #[error(transparent)]
    LoadApiKey(#[from] LoadAPIKeyError),
    /// Failed to load a setting.
    #[error(transparent)]
    LoadSetting(#[from] LoadSettingError),
    /// No content was generated by the model.
    #[error(transparent)]
    NoContentGenerated(#[from] NoContentGeneratedError),
    /// The requested model does not exist.
    #[error(transparent)]
    NoSuchModel(#[from] NoSuchModelError),
    /// Too many embedding values for a single call.
    #[error(transparent)]
    TooManyEmbeddingValues(#[from] TooManyEmbeddingValuesForCallError),
    /// Type validation failed.
    #[error(transparent)]
    TypeValidation(#[from] TypeValidationError),
    /// The requested functionality is not supported.
    #[error(transparent)]
    UnsupportedFunctionality(#[from] UnsupportedFunctionalityError),
}

impl ProviderError {
    /// Check if this error is retryable.
    pub fn is_retryable(&self) -> bool {
        match self {
            Self::ApiCall(e) => e.is_retryable,
            _ => false,
        }
    }

    /// Get the suggested retry delay, if any.
    ///
    /// Only [`APICallError`] may carry a `retry_after` hint.
    pub fn retry_after(&self) -> Option<std::time::Duration> {
        match self {
            Self::ApiCall(e) => e.retry_after,
            _ => None,
        }
    }
}

#[cfg(test)]
#[path = "provider_error.test.rs"]
mod tests;
