//! Layered configuration: settings, model selection, providers, effort, fast mode.
//!
//! Depends on coco-types for shared enums. Uses `coco_error` + typed
//! `ConfigError` (Tier 3 main-trunk policy).

pub mod analytics;
pub mod builtin;
pub mod compact_settings;
pub mod constants;
pub mod effort;
pub mod env;
pub mod error;
pub mod fast_mode;
pub mod global_config;
pub(crate) mod jsonc;
pub mod model;
pub mod overrides;
pub mod positive;
pub mod prompt_cache_settings;
pub mod provider;
pub mod runtime;
pub mod sandbox_settings;
pub mod secret;
pub mod sections;
pub mod settings;
pub mod system_reminder;
pub mod telemetry;
pub mod tool_overrides;

// Re-export key types for convenience
pub use analytics::AnalyticsPipeline;
pub use analytics::AnalyticsSink;
pub use analytics::EventProperties;
pub use analytics::MetadataValue;
pub use analytics::SessionAnalytics;
pub use builtin::DEFAULT_BASE_INSTRUCTIONS;
pub use builtin::builtin_models_partial;
pub use builtin::builtin_models_resolved;
pub use builtin::builtin_provider_partials;
pub use builtin::builtin_providers;
pub use compact_settings::ApiNativeConfig as CompactApiNativeConfig;
pub use compact_settings::AutoCompactConfig;
pub use compact_settings::CompactConfig;
pub use compact_settings::DisplayCollapseConfig;
pub use compact_settings::ExperimentalConfig as CompactExperimentalConfig;
pub use compact_settings::HistorySnipConfig;
pub use compact_settings::MicroCompactConfig;
pub use compact_settings::PartialCompactSettings;
pub use compact_settings::SessionMemoryConfig;
pub use compact_settings::StagedCompactConfig;
pub use compact_settings::TimeBasedMcConfig;
pub use env::EnvKey;
pub use env::EnvOnlyConfig;
pub use env::EnvSnapshot;
pub use error::ConfigError;
pub use error::Result;
pub(crate) use error::ResultExt;
pub use fast_mode::CooldownReason;
pub use fast_mode::FastModeState;
pub use global_config::GlobalConfig;
pub use model::FallbackRecoveryPolicy;
pub use model::ModelInfo;
pub use model::ModelRegistry;
pub use model::ModelRoles;
pub use model::ModelSelection;
pub use model::ModelSelectionSettings;
pub use model::PartialModelInfo;
pub use model::ResolvedModel;
pub use model::RoleSlots;
pub use model::build_model_registry;
pub use overrides::RuntimeOverrides;
pub use positive::PositiveCount;
pub use positive::PositiveTokens;
pub use prompt_cache_settings::AccountConfig;
pub use prompt_cache_settings::AccountKindSetting;
pub use prompt_cache_settings::PartialAccountSettings;
pub use prompt_cache_settings::PartialPromptCacheSettings;
pub use prompt_cache_settings::PromptCacheRuntimeConfig;
pub use provider::PartialProviderClientOptions;
pub use provider::PartialProviderConfig;
pub use provider::PartialProviderModelOverride;
pub use provider::ProviderClientOptions;
pub use provider::ProviderConfig;
pub use provider::ProviderModelOverride;
pub use runtime::CatalogPaths;
pub use runtime::RuntimeConfig;
pub use runtime::RuntimeConfigBuilder;
pub use runtime::RuntimePublisher;
pub use runtime::build_runtime_config;
pub use runtime::build_runtime_config_with;
pub use sandbox_settings::FilesystemConfig;
pub use sandbox_settings::IgnoreViolationsConfig;
pub use sandbox_settings::MitmProxyConfig;
pub use sandbox_settings::NetworkConfig;
pub use sandbox_settings::NetworkMode;
pub use sandbox_settings::RipgrepConfig;
pub use sandbox_settings::SandboxBypass;
pub use sandbox_settings::SandboxSettings;
pub use sandbox_settings::SourcedRule;
pub use secret::RedactedSecret;
pub use sections::ApiConfig;
pub use sections::ApiRetryConfig;
pub use sections::BashConfig;
pub use sections::LoopConfig;
pub use sections::LspConfig;
pub use sections::McpRuntimeConfig;
pub use sections::MemoryConfig;
pub use sections::PathConfig;
pub use sections::ShellConfig;
pub use sections::ToolConfig;
pub use sections::WebFetchConfig;
pub use sections::WebSearchConfig;
pub use sections::WebSearchProvider;
pub use settings::PartialLogSettings;
pub use settings::PlanModeSettings;
pub use settings::PlanModeWorkflow;
pub use settings::PlanPhase4Variant;
pub use settings::SessionSettings;
pub use settings::Settings;
pub use settings::SettingsWithSource;
pub use settings::load_settings;
pub use settings::load_settings_with;
pub use settings::policy::load_policy_settings;
pub use settings::source::SettingSource;
pub use settings::watcher::SettingsWatcher;
pub use settings::watcher::WatchedKind;
pub use system_reminder::AttachmentSettings as SystemReminderAttachmentSettings;
pub use system_reminder::DEFAULT_TIMEOUT_MS as SYSTEM_REMINDER_DEFAULT_TIMEOUT_MS;
pub use system_reminder::SystemReminderConfig;
pub use tool_overrides::resolve_tool_overrides;

pub fn parse_jsonc_value(contents: &str) -> Result<serde_json::Value> {
    jsonc::parse_value(contents)
}
