//! Context compaction: full (LLM summarize), micro (tool result clearing),
//! API-level clearing, reactive with circuit breaker, and auto-trigger.
//!
//! TS: services/compact/ (compact.ts, microCompact.ts, autoCompact.ts, apiMicrocompact.ts)

pub mod api_compact;
pub mod auto_trigger;
pub mod compact;
pub mod grouping;
pub mod micro;
pub mod micro_advanced;
pub mod observer;
pub mod post_compact_async_agents;
pub mod post_compact_files;
pub mod post_compact_plan;
pub mod post_compact_plan_mode;
pub mod post_compact_skills;
pub mod prompt;
pub mod reactive;
pub mod serialize;
pub mod session_memory;
pub mod staged;
pub mod tokens;
pub mod types;

// ── Re-exports for ergonomic use ────────────────────────────────────

pub use api_compact::ApiContextOptions;
pub use api_compact::DEFAULT_API_MAX_INPUT_TOKENS;
pub use api_compact::DEFAULT_API_TARGET_INPUT_TOKENS;
pub use api_compact::TOOLS_CLEARABLE_RESULTS;
pub use api_compact::TOOLS_EXCLUDE_FROM_CLEAR_USES;
pub use api_compact::get_api_context_management;
pub use auto_trigger::CompactQuerySource;
pub use auto_trigger::TimeBasedMcConfig;
pub use auto_trigger::TimeBasedTrigger;
pub use auto_trigger::apply_context_window_override;
pub use auto_trigger::auto_compact_threshold;
pub use auto_trigger::calculate_token_warning_state;
pub use auto_trigger::effective_context_window;
pub use auto_trigger::evaluate_time_based_trigger;
pub use auto_trigger::is_auto_compact_enabled;
pub use auto_trigger::should_auto_compact;
pub use auto_trigger::should_auto_compact_guarded;
pub use auto_trigger::should_auto_compact_guarded_with_collapse;
pub use compact::CompactRunOptions;
pub use compact::PostCompactAttachmentFn;
pub use compact::annotate_boundary_with_preserved_segment;
pub use compact::build_compact_summary_message;
pub use compact::build_post_compact_messages;
pub use compact::compact_conversation;
pub use compact::merge_hook_instructions;
pub use compact::partial_compact_conversation;
pub use compact::strip_images_from_messages;
pub use compact::strip_reinjected_attachments;
pub use compact::truncate_head_for_ptl_retry;
pub use micro::COMPACTABLE_TOOLS;
pub use micro::collect_compactable_tool_ids;
pub use micro::micro_compact;
pub use micro::time_based_microcompact;
pub use micro_advanced::MicroCompactBudgetConfig;
pub use micro_advanced::clear_file_unchanged_stubs;
pub use micro_advanced::clear_thinking_inplace;
pub use micro_advanced::clear_tool_uses_inplace;
pub use micro_advanced::compact_thinking_blocks;
pub use micro_advanced::micro_compact_with_budget;
pub use observer::CompactionObserver;
pub use observer::CompactionObserverRegistry;
pub use post_compact_async_agents::AsyncAgentSnapshot;
pub use post_compact_async_agents::create_async_agent_attachments;
pub use post_compact_files::create_post_compact_file_attachments;
pub use post_compact_files::create_post_compact_file_attachments_with_priority;
pub use post_compact_plan::create_plan_attachment_from_owned;
pub use post_compact_plan::create_plan_attachment_if_needed;
pub use post_compact_plan_mode::create_plan_mode_attachment_if_needed;
// Re-export the plan-mode attachment shape so callers can build it
// without depending directly on `coco-context`. TS callers populate it
// inline at the compact site.
pub use coco_context::PlanModeAttachment;
pub use post_compact_skills::PostCompactSkill;
pub use post_compact_skills::create_post_compact_skill_attachments;
pub use prompt::format_compact_summary;
pub use prompt::get_compact_prompt;
pub use prompt::get_compact_user_summary_message;
pub use prompt::get_partial_compact_prompt;
pub use reactive::ReactiveCompactConfig;
pub use reactive::ReactiveCompactState;
pub use reactive::api_microcompact;
pub use reactive::calculate_drop_target;
pub use reactive::peel_head_for_ptl_retry;
pub use reactive::should_reactive_compact;
pub use serialize::encode_anthropic_context_management;
pub use session_memory::SessionMemoryCompactConfig;
pub use session_memory::SessionMemoryExtractionInputs;
pub use session_memory::SessionMemoryExtractionThresholds;
pub use session_memory::adjust_index_to_preserve_api_invariants;
pub use session_memory::compact_session_memory;
pub use session_memory::has_text_blocks;
pub use session_memory::merge_similar_memories;
pub use session_memory::select_memories_for_compaction;
pub use session_memory::should_extract_memory;
pub use staged::CommitEntry as StagedCommitEntry;
pub use staged::SnapshotEntry as StagedSnapshotEntry;
pub use staged::StagedCompactLedger;
pub use staged::StagedRange;
pub use staged::apply_collapses_if_needed;
pub use staged::placeholder_text as staged_placeholder_text;
pub use tokens::estimate_message_tokens;
pub use tokens::estimate_tokens;
pub use tokens::estimate_tokens_conservative;
pub use types::ClearToolInputs;
pub use types::CompactError;
pub use types::CompactResult;
pub use types::CompactWarningState;
pub use types::ContextEditStrategy;
pub use types::MicrocompactResult;
pub use types::ThinkingKeep;
pub use types::TokenWarningState;
pub use types::ToolUseKeep;
pub use types::extract_discovered_tool_names;
