[build]
rustc-wrapper = "sccache"

[env]
SCCACHE_CACHE_SIZE = "20G"
SCCACHE_IDLE_TIMEOUT = "0"

[profile.dev]
incremental = false

[profile.test]
incremental = false

[profile.ci]
incremental = false

[profile.ci-test]
incremental = false

[target.'cfg(all(windows, target_env = "msvc"))']
rustflags = ["-C", "link-arg=/STACK:8388608"]

[target.'cfg(all(windows, target_env = "gnu"))']
rustflags = ["-C", "link-arg=-Wl,--stack,8388608"]
