/// Builder for loop iteration prompts.
///
/// Implements Auto-Coder style git-based iterative improvement prompts.
pub struct LoopPromptBuilder;

/// Default loop instruction appended to queries after first iteration.
const DEFAULT_LOOP_INSTRUCTION: &str = r#"
Additional instruction: use git log to get the code changes generated by previous
tasks and try to focus on iterative improvements and refinements and make sure to
use git commit command to make a commit after every single file edit."#;

impl LoopPromptBuilder {
    /// Enhance query for loop iterations > 0.
    ///
    /// First iteration (iteration == 0) uses original query unchanged.
    /// Subsequent iterations append loop instructions.
    ///
    /// # Arguments
    ///
    /// * `original` - Original user query
    /// * `iteration` - Current iteration number (0-indexed)
    ///
    /// # Returns
    ///
    /// Enhanced query string
    pub fn build(original: &str, iteration: i32) -> String {
        if iteration == 0 {
            original.to_string()
        } else {
            Self::enhance(original)
        }
    }

    /// Enhance query with loop instructions.
    ///
    /// Appends git-based iterative improvement instructions.
    pub fn enhance(original: &str) -> String {
        format!("{original}\n{DEFAULT_LOOP_INSTRUCTION}")
    }

    /// Build with custom loop instruction.
    ///
    /// Allows users to specify their own loop prompt.
    pub fn build_with_custom(
        original: &str,
        iteration: i32,
        custom_instruction: Option<&str>,
    ) -> String {
        if iteration == 0 {
            original.to_string()
        } else {
            match custom_instruction {
                Some(instruction) => format!("{original}\n\n{instruction}"),
                None => Self::enhance(original),
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn first_iteration_unchanged() {
        let query = "Implement user auth";
        assert_eq!(LoopPromptBuilder::build(query, 0), query);
    }

    #[test]
    fn subsequent_iterations_enhanced() {
        let query = "Implement user auth";
        let enhanced = LoopPromptBuilder::build(query, 1);

        assert!(enhanced.starts_with(query));
        assert!(enhanced.contains("git log"));
        assert!(enhanced.contains("iterative improvements"));
    }

    #[test]
    fn custom_instruction() {
        let query = "Fix tests";
        let custom = "Focus on edge cases and error handling";
        let result = LoopPromptBuilder::build_with_custom(query, 1, Some(custom));

        assert!(result.contains(query));
        assert!(result.contains(custom));
        assert!(!result.contains("git log")); // No default instruction
    }
}
