"""cocode SDK — programmatic access to the cocode multi-provider LLM CLI.

Two usage patterns:

1. One-shot query (simplest)::

    from cocode_sdk import query

    async for event in query("Fix the bug"):
        print(event.method, event.params)

2. Multi-turn client::

    from cocode_sdk import CocodeClient

    async with CocodeClient(prompt="Fix the bug") as client:
        async for event in client.events():
            print(event.method)
        async for event in client.send("Now add tests"):
            print(event.method)
"""

from cocode_sdk.client import CanUseTool, CocodeClient, HookHandler
from cocode_sdk.decorators import HookDefinition, hook
from cocode_sdk.errors import (
    CLIConnectionError,
    CLINotFoundError,
    CocodeSDKError,
    JSONDecodeError,
    ProcessError,
    SessionNotFoundError,
    TransportClosedError,
)
from cocode_sdk.structured import TypedClient
from cocode_sdk.tools import ToolDefinition, tool
from cocode_sdk.generated.protocol import (
    AgentDefinitionConfig,
    AgentHookConfig,
    AgentIsolationMode,
    AgentMemoryScope,
    AgentMessageDeltaParams,
    AgentMessageItem,
    AgentsKilledParams,
    AgentsRegisteredParams,
    ApprovalDecision,
    AskForApprovalParams,
    ClientInfo,
    CommandDequeuedParams,
    CommandExecutionItem,
    CommandInfo,
    CommandQueuedParams,
    CompactionFailedParams,
    CompactionStartedParams,
    ContextClearedParams,
    ContextCompactedParams,
    ContextUsageWarningParams,
    CostWarningParams,
    ErrorCategory,
    ErrorItem,
    ErrorNotificationParams,
    FastModeChangedParams,
    FileChange,
    FileChangeItem,
    FileChangeKind,
    GenericToolCallItem,
    HookBehavior,
    HookCallbackConfig,
    HookCallbackOutput,
    HookCallbackParams,
    HookExecutedParams,
    HookMatcherConfig,
    HttpMcpServerConfig,
    IdeDiagnosticsUpdatedParams,
    IdeSelectionChangedParams,
    InitializeCapabilities,
    ItemEventParams,
    ItemStatus,
    KeepAliveNotifParams,
    MaxTurnsReachedParams,
    McpRouteMessageParams,
    McpServerFailure,
    McpServerInfoParams,
    McpStartupCompleteParams,
    McpStartupStatusParams,
    McpToolCallError,
    McpToolCallItem,
    McpToolCallResult,
    ModelFallbackCompletedParams,
    ModelFallbackStartedParams,
    NotificationHookInput,
    PermissionModeChangedParams,
    PermissionRequestHookInput,
    PermissionSuggestion,
    PlanModeChangedParams,
    PostToolUseFailureHookInput,
    PostToolUseHookInput,
    PreCompactHookInput,
    PreToolUseHookInput,
    PromptSuggestionParams,
    QueueStateChangedParams,
    RateLimitParams,
    ReasoningDeltaParams,
    ReasoningItem,
    RequestUserInputParams,
    RewindCompletedParams,
    RewindFailedParams,
    SandboxStateChangedParams,
    SandboxViolationsDetectedParams,
    ServerCancelRequestParams,
    ServerNotification,
    ServerRequest,
    SessionEndedParams,
    SessionEndedReason,
    SessionEndHookInput,
    SessionResultParams,
    SessionStartedParams,
    SessionStartHookInput,
    SessionSummary,
    SseMcpServerConfig,
    StdioMcpServerConfig,
    StopHookInput,
    StreamRequestEndParams,
    StreamStallDetectedParams,
    StreamWatchdogWarningParams,
    SubagentBackgroundedParams,
    SubagentCompletedParams,
    SubagentItem,
    SubagentProgressParams,
    SubagentStartHookInput,
    SubagentStopHookInput,
    SubagentSpawnedParams,
    SummarizeCompletedParams,
    SummarizeFailedParams,
    TaskCompletedParams,
    TaskProgressParams,
    TaskStartedParams,
    ThreadItem,
    TurnCompletedParams,
    TurnFailedParams,
    TurnInterruptedNotifParams,
    TurnRetryParams,
    TurnStartedParams,
    Usage,
    UserPromptSubmitHookInput,
    WebSearchItem,
)
from cocode_sdk.query import query

__version__ = "0.1.0"

__all__ = [
    "__version__",
    # Functions
    "query",
    # Client
    "CanUseTool",
    "CocodeClient",
    "HookHandler",
    "TypedClient",
    # Decorators
    "tool",
    "ToolDefinition",
    "hook",
    "HookDefinition",
    # Errors
    "CocodeSDKError",
    "CLINotFoundError",
    "CLIConnectionError",
    "ProcessError",
    "JSONDecodeError",
    "TransportClosedError",
    "SessionNotFoundError",
    # Config types
    "AgentDefinitionConfig",
    "AgentHookConfig",
    "AgentIsolationMode",
    "AgentMemoryScope",
    "ClientInfo",
    "CommandInfo",
    "HookCallbackConfig",
    "HookMatcherConfig",
    "HttpMcpServerConfig",
    "InitializeCapabilities",
    "SseMcpServerConfig",
    "StdioMcpServerConfig",
    # Notification types
    "ServerNotification",
    "AgentMessageDeltaParams",
    "AgentsKilledParams",
    "AgentsRegisteredParams",
    "CommandDequeuedParams",
    "CommandQueuedParams",
    "CompactionFailedParams",
    "CompactionStartedParams",
    "ContextClearedParams",
    "ContextCompactedParams",
    "ContextUsageWarningParams",
    "CostWarningParams",
    "ErrorNotificationParams",
    "FastModeChangedParams",
    "HookExecutedParams",
    "IdeDiagnosticsUpdatedParams",
    "IdeSelectionChangedParams",
    "ItemEventParams",
    "KeepAliveNotifParams",
    "MaxTurnsReachedParams",
    "McpServerFailure",
    "McpServerInfoParams",
    "McpStartupCompleteParams",
    "McpStartupStatusParams",
    "ModelFallbackCompletedParams",
    "ModelFallbackStartedParams",
    "PermissionModeChangedParams",
    "PlanModeChangedParams",
    "QueueStateChangedParams",
    "RateLimitParams",
    "ReasoningDeltaParams",
    "RewindCompletedParams",
    "RewindFailedParams",
    "SandboxStateChangedParams",
    "SandboxViolationsDetectedParams",
    "SessionEndedParams",
    "SessionStartedParams",
    "StreamRequestEndParams",
    "StreamStallDetectedParams",
    "StreamWatchdogWarningParams",
    "SubagentBackgroundedParams",
    "SubagentCompletedParams",
    "SubagentProgressParams",
    "SubagentSpawnedParams",
    "SummarizeCompletedParams",
    "SummarizeFailedParams",
    "TaskCompletedParams",
    "TaskProgressParams",
    "TaskStartedParams",
    "TurnCompletedParams",
    "TurnFailedParams",
    "TurnInterruptedNotifParams",
    "TurnRetryParams",
    "TurnStartedParams",
    # Server request types
    "ServerRequest",
    "AskForApprovalParams",
    "HookCallbackParams",
    "McpRouteMessageParams",
    "RequestUserInputParams",
    "ServerCancelRequestParams",
    # Item types
    "ThreadItem",
    "AgentMessageItem",
    "CommandExecutionItem",
    "ErrorItem",
    "FileChange",
    "FileChangeItem",
    "FileChangeKind",
    "GenericToolCallItem",
    "McpToolCallError",
    "McpToolCallItem",
    "McpToolCallResult",
    "ReasoningItem",
    "SubagentItem",
    "WebSearchItem",
    # Enums
    "ApprovalDecision",
    "ErrorCategory",
    "HookBehavior",
    "ItemStatus",
    "SessionEndedReason",
    # Hook input/output types
    "HookCallbackOutput",
    "PreToolUseHookInput",
    "PostToolUseHookInput",
    "PostToolUseFailureHookInput",
    "PreCompactHookInput",
    "PermissionRequestHookInput",
    "StopHookInput",
    "SubagentStartHookInput",
    "SubagentStopHookInput",
    "UserPromptSubmitHookInput",
    "NotificationHookInput",
    "SessionStartHookInput",
    "SessionEndHookInput",
    # Session types
    "SessionResultParams",
    "SessionSummary",
    "PromptSuggestionParams",
    "PermissionSuggestion",
    # Usage
    "Usage",
]
